package me.amuxix.items.armour

import me.amuxix.items.Item

sealed abstract class Shield(dropLevel: Int) extends Item(dropLevel, "Shield")

//Armour
object SplinteredTowerShield extends Shield(1)
object CorrodedTowerShield extends Shield(5)
object RawhideTowerShield extends Shield(11)
object CedarTowerShield extends Shield(17)
object CopperTowerShield extends Shield(24)
object ReinforcedTowerShield extends Shield(30)
object PaintedTowerShield extends Shield(35)
object BuckskinTowerShield extends Shield(39)
object MahoganyTowerShield extends Shield(43)
object BronzeTowerShield extends Shield(47)
object GirdedTowerShield extends Shield(51)
object CrestedTowerShield extends Shield(55)
object ShagreenTowerShield extends Shield(58)
object EbonyTowerShield extends Shield(61)
object EzomyteTowerShield extends Shield(64)
object ColossalTowerShield extends Shield(67)
object PinnacleTowerShield extends Shield(70)

//Evasion
object GoathideBuckler extends Shield(2)
object PineBuckler extends Shield(8)
object PaintedBuckler extends Shield(16)
object HammeredBuckler extends Shield(23)
object WarBuckler extends Shield(29)
object GildedBuckler extends Shield(34)
object OakBuckler extends Shield(38)
object EnameledBuckler extends Shield(42)
object CorrugatedBuckler extends Shield(46)
object BattleBuckler extends Shield(50)
object GoldenBuckler extends Shield(54)
object IronwoodBuckler extends Shield(57)
object LacqueredBuckler extends Shield(60)
object VaalBuckler extends Shield(63)
object CrusaderBuckler extends Shield(66)
object ImperialBuckler extends Shield(69)

//ES
object TwigSpiritShield extends Shield(3)
object YewSpiritShield extends Shield(9)
object BoneSpiritShield extends Shield(15)
object TarnishedSpiritShield extends Shield(23)
object JinglingSpiritShield extends Shield(28)
object BrassSpiritShield extends Shield(33)
object WalnutSpiritShield extends Shield(37)
object IvorySpiritShield extends Shield(41)
object AncientSpiritShield extends Shield(45)
object ChimingSpiritShield extends Shield(49)
object ThoriumSpiritShield extends Shield(53)
object LacewoodSpiritShield extends Shield(56)
object FossilisedSpiritShield extends Shield(59)
object VaalSpiritShield extends Shield(62)
object HarmonicSpiritShield extends Shield(65)
object TitaniumSpiritShield extends Shield(68)

//Armour+Evasion
object RottedRoundShield extends Shield(5)
object FirRoundShield extends Shield(12)
object StuddedRoundShield extends Shield(20)
object ScarletRoundShield extends Shield(27)
object SplendidRoundShield extends Shield(33)
object MapleRoundShield extends Shield(39)
object SpikedRoundShield extends Shield(45)
object CrimsonRoundShield extends Shield(49)
object BaroqueRoundShield extends Shield(54)
object TeakRoundShield extends Shield(58)
object SpinyRoundShield extends Shield(62)
object CardinalRoundShield extends Shield(66)
object ElegantRoundShield extends Shield(70)

//Armour+ES
object PlankKiteShield extends Shield(7)
object LindenKiteShield extends Shield(13)
object ReinforcedKiteShield extends Shield(20)
object LayeredKiteShield extends Shield(27)
object CeremonialKiteShield extends Shield(34)
object EtchedKiteShield extends Shield(40)
object SteelKiteShield extends Shield(46)
object LaminatedKiteShield extends Shield(50)
object AngelicKiteShield extends Shield(55)
object BrandedKiteShield extends Shield(59)
object ChampionKiteShield extends Shield(62)
object MosaicKiteShield extends Shield(65)
object ArchonKiteShield extends Shield(68)

//Evasion+ES
object SpikedBundle extends Shield(5)
object DriftwoodSpikedShield extends Shield(12)
object AlloyedSpikedShield extends Shield(20)
object BurnishedSpikedShield extends Shield(27)
object OrnateSpikedShield extends Shield(33)
object RedwoodSpikedShield extends Shield(39)
object CompoundSpikedShield extends Shield(45)
object PolishedSpikedShield extends Shield(49)
object SovereignSpikedShield extends Shield(54)
object AlderSpikedShield extends Shield(58)
object EzomyteSpikedShield extends Shield(62)
object MirroredSpikedShield extends Shield(66)
object SupremeSpikedShield extends Shield(70)