package me.amuxix.items.weapons

import me.amuxix.items.Item

sealed abstract class Axe(dropLevel: Int, `class`: String) extends Item(dropLevel, `class` + " Axe")

sealed abstract class OneHandedAxe(dropLevel: Int) extends Axe(dropLevel, "Two Handed")

object RustedHatchet extends OneHandedAxe(2)
object JadeHatchet extends OneHandedAxe(6)
object BoardingAxe extends OneHandedAxe(11)
object Cleaver extends OneHandedAxe(16)
object BroadAxe extends OneHandedAxe(21)
object ArmingAxe extends OneHandedAxe(25)
object DecorativeAxe extends OneHandedAxe(29)
object SpectralAxe extends OneHandedAxe(33)
object EtchedHatchet extends OneHandedAxe(35)
object JasperAxe extends OneHandedAxe(36)
object Tomahawk extends OneHandedAxe(39)
object WristChopper extends OneHandedAxe(42)
object WarAxe extends OneHandedAxe(45)
object ChestSplitter extends OneHandedAxe(48)
object CeremonialAxe extends OneHandedAxe(51)
object WraithAxe extends OneHandedAxe(54)
object EngravedHatchet extends OneHandedAxe(56)
object KaruiAxe extends OneHandedAxe(57)
object SiegeAxe extends OneHandedAxe(59)
object ReaverAxe extends OneHandedAxe(61)
object ButcherAxe extends OneHandedAxe(63)
object VaalHatchet extends OneHandedAxe(65)
object RoyalAxe extends OneHandedAxe(67)
object InfernalAxe extends OneHandedAxe(69)
object RunicHatchet extends OneHandedAxe(71)

sealed abstract class TwoHandedAxe(dropLevel: Int) extends Axe(dropLevel, "Two Handed")

object StoneAxe extends TwoHandedAxe(4)
object JadeChopper extends TwoHandedAxe(9)
object Woodsplitter extends TwoHandedAxe(13)
object Poleaxe extends TwoHandedAxe(18)
object DoubleAxe extends TwoHandedAxe(23)
object GildedAxe extends TwoHandedAxe(28)
object ShadowAxe extends TwoHandedAxe(33)
object DaggerAxe extends TwoHandedAxe(36)
object JasperChopper extends TwoHandedAxe(37)
object TimberAxe extends TwoHandedAxe(41)
object HeadsmanAxe extends TwoHandedAxe(45)
object Labrys extends TwoHandedAxe(49)
object NobleAxe extends TwoHandedAxe(52)
object AbyssalAxe extends TwoHandedAxe(55)
object KaruiChopper extends TwoHandedAxe(58)
object TalonAxe extends TwoHandedAxe(59)
object SunderingAxe extends TwoHandedAxe(60)
object EzomyteAxe extends TwoHandedAxe(62)
object VaalAxe extends TwoHandedAxe(64)
object DespotAxe extends TwoHandedAxe(66)
object VoidAxe extends TwoHandedAxe(68)
object Fleshripper extends TwoHandedAxe(70)