package me.amuxix.items.weapons

import me.amuxix.items.Item

sealed abstract class Mace(dropLevel: Int, `class`: String) extends Item(dropLevel, `class` + " Mace")

sealed abstract class OneHandedMace(dropLevel: Int) extends Mace(dropLevel, "One Handed")

object DriftwoodClub extends OneHandedMace(1)
object TribalClub extends OneHandedMace(5)
object SpikedClub extends OneHandedMace(10)
object StoneHammer extends OneHandedMace(15)
object WarHammer extends OneHandedMace(20)
object BladedMace extends OneHandedMace(24)
object CeremonialMace extends OneHandedMace(28)
object DreamMace extends OneHandedMace(32)
object WyrmMace extends OneHandedMace(34)
object PetrifiedClub extends OneHandedMace(35)
object BarbedClub extends OneHandedMace(38)
object RockBreaker extends OneHandedMace(41)
object BattleHammer extends OneHandedMace(44)
object FlangedMace extends OneHandedMace(47)
object OrnateMace extends OneHandedMace(50)
object PhantomMace extends OneHandedMace(53)
object DragonMace extends OneHandedMace(55)
object AncestralClub extends OneHandedMace(56)
object Tenderizer extends OneHandedMace(58)
object Gavel extends OneHandedMace(60)
object LegionHammer extends OneHandedMace(62)
object Pernarch extends OneHandedMace(64)
object AuricMace extends OneHandedMace(66)
object NightmareMace extends OneHandedMace(68)
object BehemothMace extends OneHandedMace(70)


sealed abstract class TwoHandedMace(dropLevel: Int) extends Mace(dropLevel, "Two Handed")

object DriftwoodMaul extends TwoHandedMace(3)
object TribalMaul extends TwoHandedMace(8)
object Mallet extends TwoHandedMace(12)
object Sledgehammer extends TwoHandedMace(17)
object JaggedMaul extends TwoHandedMace(22)
object BrassMaul extends TwoHandedMace(27)
object FrightMaul extends TwoHandedMace(32)
object MorningStar extends TwoHandedMace(34)
object TotemicMaul extends TwoHandedMace(36)
object GreatMallet extends TwoHandedMace(40)
object Steelhead extends TwoHandedMace(44)
object SpinyMaul extends TwoHandedMace(48)
object PlatedMaul extends TwoHandedMace(51)
object DreadMaul extends TwoHandedMace(54)
object SolarMaul extends TwoHandedMace(56)
object KaruiMaul extends TwoHandedMace(57)
object ColossusMallet extends TwoHandedMace(59)
object Piledriver extends TwoHandedMace(61)
object Meatgrinder extends TwoHandedMace(63)
object ImperialMaul extends TwoHandedMace(65)
object TerrorMaul extends TwoHandedMace(67)
object CoronalMaul extends TwoHandedMace(69)