INSERT INTO uniques (name, base)
VALUES
  ('Soul Ripper', 'Quartz Flask'),
  ('Bottled Faith', 'Sulphur Flask'),
  ('Dying Sun', 'Ruby Flask'),
  ('Cinderswallow Urn', 'Silver Flask'),
  ('Taste of Hate', 'Sapphire Flask'),
  ('Sin''s Rebirth', 'Stibnite Flask'),
  ('Vessel of Vinktar', 'Topaz Flask'),
  ('Zerphi''s Last Breath', 'Grand Mana Flask'),
  ('The Wise Oak', 'Bismuth Flask'),
  ('Blood of the Karui', 'Sanctified Life Flask'),
  ('Coruscating Elixir', 'Ruby Flask'),
  ('Witchfire Brew', 'Stibnite Flask'),
  ('Lavianga''s Spirit', 'Sanctified Mana Flask'),
  ('Lion''s Roar', 'Granite Flask'),
  ('Rumi''s Concoction', 'Granite Flask'),
  ('Atziri''s Promise', 'Amethyst Flask'),
  ('Divination Distillate', 'Large Hybrid Flask'),
  ('The Writhing Jar', 'Hallowed Hybrid Flask'),
  ('Coralito''s Signature', 'Diamond Flask'),
  ('Forbidden Taste', 'Quartz Flask'),
  ('Kiara''s Determination', 'Silver Flask'),
  ('Rotgut', 'Quicksilver Flask'),
  ('Soul Catcher', 'Quartz Flask'),
  ('The Overflowing Chalice', 'Sulphur Flask'),
  ('Doedre''s Elixir', 'Greater Mana Flask'),
  ('The Sorrow of the Divine', 'Sulphur Flask'),
  ('Duskdawn', 'Maelström Staff'),
  ('Void Battery', 'Prophecy Wand'),
  ('Shade of Solaris', 'Sage Wand'),
  ('United in Dream', 'Cutlass'),
  ('Arborix', 'Assassin Bow'),
  ('Windripper', 'Imperial Bow'),
  ('Starforge', 'Infernal Sword'),
  ('Grelwood Shank', 'Eternal Sword'),
  ('Martyr of Innocence', 'Highborn Staff'),
  ('Arakaali''s Fang', 'Fiend Dagger'),
  ('Uul-Netol''s Embrace', 'Vaal Axe'),
  ('The Grey Spire', 'Judgement Staff'),
  ('Voidforge', 'Infernal Sword'),
  ('Cospri''s Malice', 'Jewelled Foil'),
  ('Disintegrator', 'Maelström Staff'),
  ('Hand of Wisdom and Action', 'Imperial Claw'),
  ('Doryani''s Catalyst', 'Vaal Sceptre'),
  ('Rigwald''s Savagery', 'Royal Axe'),
  ('Breath of the Council', 'Carnal Sceptre'),
  ('Paradoxica', 'Vaal Rapier'),
  ('Atziri''s Disfavour', 'Vaal Axe'),
  ('Rigwald''s Command', 'Midnight Blade'),
  ('Razor of the Seventh Sun', 'Midnight Blade'),
  ('Tulfall', 'Tornado Wand'),
  ('Fate of the Vaal', 'Gemstone Sword'),
  ('Cerberus Limb', 'Blood Sceptre'),
  ('Soulwrest', 'Ezomyte Staff'),
  ('The Poet''s Pen', 'Carved Wand'),
  ('Kingmaker', 'Despot Axe'),
  ('The Rippling Thoughts', 'Legion Sword'),
  ('The Crimson Storm', 'Steelwood Bow'),
  ('The Dancing Duo', 'Reaver Sword'),
  ('The Goddess Scorned', 'Elegant Sword'),
  ('Varunastra', 'Vaal Blade'),
  ('Dreadbeak', 'Rusted Sword'),
  ('Death''s Opus', 'Death Bow'),
  ('Dreadsurge', 'Cleaver'),
  ('The Scourge', 'Terror Claw'),
  ('The Tempest', 'Long Bow'),
  ('Beltimber Blade', 'Eternal Sword'),
  ('Realm Ender', 'Iron Staff'),
  ('Spine of the First Claimant', 'Iron Sceptre'),
  ('Nebuloch', 'Nightmare Mace'),
  ('Cameria''s Avarice', 'Gavel'),
  ('Soul Taker', 'Siege Axe'),
  ('The Gryphon', 'Jade Hatchet'),
  ('Silverbough', 'Crude Bow'),
  ('Corona Solaris', 'Crystal Wand'),
  ('Doomfletch''s Prism', 'Royal Bow'),
  ('Queen''s Escape', 'Ornate Sword'),
  ('Sanguine Gambol', 'Skinning Knife'),
  ('Severed in Sleep', 'Cutlass'),
  ('The Cauteriser', 'Woodsplitter'),
  ('The Enmity Divine', 'Imperial Staff'),
  ('The Stormwall', 'Royal Staff'),
  ('Xirgil''s Crank', 'Coiled Staff'),
  ('Xoph''s Nurture', 'Citadel Bow'),
  ('Mjölner', 'Gavel'),
  ('Shimmeron', 'Tornado Wand'),
  ('Tidebreaker', 'Imperial Maul'),
  ('Agnerod East', 'Imperial Staff'),
  ('Agnerod North', 'Imperial Staff'),
  ('Agnerod South', 'Imperial Staff'),
  ('Agnerod West', 'Imperial Staff'),
  ('Amplification Rod', 'Spiraled Wand'),
  ('Bloodseeker', 'Hellion''s Paw'),
  ('Brutus'' Lead Sprinkler', 'Ritual Sceptre'),
  ('Chaber Cairn', 'Great Mallet'),
  ('Geofri''s Devotion', 'Brass Maul'),
  ('Kitava''s Feast', 'Void Axe'),
  ('Mirebough', 'Gnarled Branch'),
  ('Slivertongue', 'Harbinger Bow'),
  ('The Harvest', 'Jasper Chopper'),
  ('Trypanon', 'Great Mallet'),
  ('Brightbeak', 'War Hammer'),
  ('Ahn''s Might', 'Midnight Blade'),
  ('Apep''s Rage', 'Opal Wand'),
  ('Augyre', 'Void Sceptre'),
  ('Axiom Perpetuum', 'Bronze Sceptre'),
  ('Balefire', 'Opal Sceptre'),
  ('Brain Rattler', 'Meatgrinder'),
  ('Chin Sol', 'Assassin Bow'),
  ('Divinarius', 'Imperial Skean'),
  ('Doon Cuebiyari', 'Vaal Sceptre'),
  ('Edge of Madness', 'Etched Greatsword'),
  ('Hand of Thought and Motion', 'Blinder'),
  ('Heartbreaker', 'Royal Skean'),
  ('Hegemony''s Era', 'Judgement Staff'),
  ('Hopeshredder', 'Ranger Bow'),
  ('Hrimnor''s Dirge', 'Sledgehammer'),
  ('Ichimonji', 'Corsair Sword'),
  ('Innsbury Edge', 'Elder Sword'),
  ('Izaro''s Dilemma', 'Imperial Claw'),
  ('Lifesprig', 'Driftwood Wand'),
  ('Lioneye''s Glare', 'Imperial Bow'),
  ('Ngamahu''s Flame', 'Abyssal Axe'),
  ('Panquetzaliztli', 'Jagged Maul'),
  ('Piscator''s Vigil', 'Tornado Wand'),
  ('Pledge of Hands', 'Judgement Staff'),
  ('Quill Rain', 'Short Bow'),
  ('Reach of the Council', 'Spine Bow'),
  ('Singularity', 'Platinum Sceptre'),
  ('Story of the Vaal', 'Variscite Blade'),
  ('The Dark Seer', 'Shadow Sceptre'),
  ('The Searing Touch', 'Lathi'),
  ('The Tempestuous Steel', 'War Sword'),
  ('Touch of Anguish', 'Imperial Claw'),
  ('Tulborn', 'Spiraled Wand'),
  ('Uul-Netol''s Kiss', 'Labrys'),
  ('Vulconus', 'Demon Dagger'),
  ('Xoph''s Inception', 'Bone Bow'),
  ('Jorrhast''s Blacksteel', 'Steelhead'),
  ('Allure', 'Vaal Claw'),
  ('Ashcaller', 'Quartz Wand'),
  ('Bino''s Kitchen Knife', 'Slaughter Knife'),
  ('Cane of Unravelling', 'Ezomyte Staff'),
  ('Chitus'' Needle', 'Elegant Foil'),
  ('Clayshaper', 'Rock Breaker'),
  ('Death''s Hand', 'Karui Sceptre'),
  ('Doomsower', 'Lion Sword'),
  ('Dreamfeather', 'Eternal Sword'),
  ('Dying Breath', 'Iron Staff'),
  ('Earendel''s Embrace', 'Grinning Fetish'),
  ('Hyaon''s Fury', 'Legion Sword'),
  ('Kaom''s Primacy', 'Karui Chopper'),
  ('Last Resort', 'Nailed Fist'),
  ('Midnight Bargain', 'Engraved Wand'),
  ('Mon''tregul''s Grasp', 'Void Sceptre'),
  ('Mortem Morsu', 'Fright Claw'),
  ('Ornament of the East', 'Gut Ripper'),
  ('Oro''s Sacrifice', 'Infernal Sword'),
  ('Rive', 'Terror Claw'),
  ('Sire of Shards', 'Serpentine Staff'),
  ('Taryn''s Shiver', 'Maelström Staff'),
  ('The Goddess Bound', 'Whalebone Rapier'),
  ('The Screaming Eagle', 'Jade Hatchet'),
  ('The Supreme Truth', 'Crystal Sceptre'),
  ('The Wasp Nest', 'Throat Stabber'),
  ('Voltaxic Rift', 'Spine Bow'),
  ('Jack, the Axe', 'Vaal Hatchet'),
  ('Terminus Est', 'Tiger Sword'),
  ('Hiltless', 'Reaver Sword'),
  ('Queen''s Decree', 'Ornate Sword'),
  ('Lakishu''s Blade', 'Elegant Sword'),
  ('Mark of the Doubting Knight', 'Platinum Kris'),
  ('Prismatic Eclipse', 'Twilight Blade'),
  ('The Princess', 'Sabre'),
  ('Lavianga''s Wisdom', 'War Hammer'),
  ('Advancing Fortress', 'Gut Ripper'),
  ('Callinellus Malleus', 'Auric Mace'),
  ('Chober Chaber', 'Great Mallet'),
  ('Daresso''s Passion', 'Estoc'),
  ('Death''s Harp', 'Death Bow'),
  ('Debeon''s Dirge', 'Despot Axe'),
  ('Doomfletch', 'Royal Bow'),
  ('Dyadus', 'Infernal Axe'),
  ('Ephemeral Edge', 'Dusk Blade'),
  ('Essentia Sanguis', 'Vaal Claw'),
  ('Ewar''s Mirage', 'Antique Rapier'),
  ('Femurs of the Saints', 'Primordial Staff'),
  ('Fidelitas'' Spike', 'Jagged Foil'),
  ('Flesh-Eater', 'Dream Mace'),
  ('Hezmana''s Bloodlust', 'Vaal Axe'),
  ('Kondo''s Pride', 'Ezomyte Blade'),
  ('Kongor''s Undying Rage', 'Terror Maul'),
  ('Moonbender''s Wing', 'Tomahawk'),
  ('Null''s Inclination', 'Ranger Bow'),
  ('Nuro''s Harp', 'Harbinger Bow'),
  ('Nycta''s Lantern', 'Crystal Sceptre'),
  ('Obliteration', 'Demon''s Horn'),
  ('Quecholli', 'Jagged Maul'),
  ('Reaper''s Pursuit', 'Shadow Axe'),
  ('Rebuke of the Vaal', 'Vaal Blade'),
  ('Redbeak', 'Rusted Sword'),
  ('Reverberation Rod', 'Spiraled Wand'),
  ('Rigwald''s Charge', 'Highland Blade'),
  ('Scaeva', 'Gladius'),
  ('Silverbranch', 'Crude Bow'),
  ('Sinvicta''s Mettle', 'Ezomyte Axe'),
  ('Storm Cloud', 'Long Bow'),
  ('Storm Prison', 'Carved Wand'),
  ('Taproot', 'Ambusher'),
  ('The Blood Reaper', 'Headsman Axe'),
  ('The Consuming Dark', 'Fiend Dagger'),
  ('The Dancing Dervish', 'Reaver Sword'),
  ('The Whispering Ice', 'Vile Staff'),
  ('White Wind', 'Imperial Skean'),
  ('Widowmaker', 'Boot Blade'),
  ('Wings of Entropy', 'Sundering Axe'),
  ('Al Dhih', 'Timeworn Claw'),
  ('Aurumvorax', 'Basket Rapier'),
  ('Bloodplay', 'Stiletto'),
  ('Cybil''s Paw', 'Thresher Claw'),
  ('Dreadarc', 'Cleaver'),
  ('Eclipse Solaris', 'Crystal Wand'),
  ('Frostbreath', 'Ornate Mace'),
  ('Infractem', 'Decimation Bow'),
  ('Limbsplit', 'Woodsplitter'),
  ('Marohi Erqi', 'Karui Maul'),
  ('Mightflay', 'Flaying Knife'),
  ('Moonsorrow', 'Imbued Wand'),
  ('Wideswing', 'Poleaxe'),
  ('Wildslash', 'Awl'),
  ('Pillar of the Caged God', 'Long Staff'),
  ('Relentless Fury', 'Decorative Axe'),
  ('Tremor Rod', 'Military Staff'),
  ('Darkscorn', 'Assassin Bow'),
  ('Bitterdream', 'Shadow Sceptre'),
  ('Realmshaper', 'Iron Staff'),
  ('Geofri''s Baptism', 'Brass Maul'),
  ('Gorebreaker', 'Spiked Club'),
  ('The Blood Thorn', 'Gnarled Branch'),
  ('Ungil''s Gauche', 'Boot Knife'),
  ('Cameria''s Maul', 'Gavel'),
  ('Goredrill', 'Skinning Knife'),
  ('Hrimnor''s Hymn', 'Sledgehammer'),
  ('Iron Commander', 'Death Bow'),
  ('The Stormheart', 'Royal Staff'),
  ('Fencoil', 'Gnarled Branch'),
  ('Twyzel', 'Sage Wand'),
  ('Voidhome', 'Dread Maul'),
  ('Abberath''s Horn', 'Goat''s Horn'),
  ('Roth''s Reach', 'Recurve Bow'),
  ('Shiversting', 'Bastard Sword'),
  ('Atziri''s Reflection', 'Golden Buckler'),
  ('Farrul''s Fur', 'Triumphant Lamellar'),
  ('The Devouring Diadem', 'Necromancer Circlet'),
  ('The Queen''s Hunger', 'Vaal Regalia'),
  ('Skyforth', 'Sorcerer Boots'),
  ('Inpulsa''s Broken Heart', 'Sadist Garb'),
  ('Shavronne''s Wrappings', 'Occultist''s Vestment'),
  ('Rigwald''s Quills', 'Two-Point Arrow Quiver'),
  ('Apep''s Supremacy', 'Vaal Spirit Shield'),
  ('The Eternity Shroud', 'Blood Raiment'),
  ('Seven-League Step', 'Rawhide Boots'),
  ('Atziri''s Acuity', 'Vaal Gauntlets'),
  ('Command of the Pit', 'Riveted Gloves'),
  ('Kaom''s Heart', 'Glorious Plate'),
  ('Goldwyrm', 'Nubuck Boots'),
  ('Bubonic Trail', 'Murder Boots'),
  ('Tombfist', 'Steelscale Gauntlets'),
  ('Loreweave', 'Elegant Ringmail'),
  ('The Tempest''s Binding', 'Callous Mask'),
  ('Fenumus'' Shroud', 'Widowsilk Robe'),
  ('Shroud of the Lightless', 'Carnal Armour'),
  ('Atziri''s Splendour', 'Sacrificial Garb'),
  ('Light of Lunaris', 'Jingling Spirit Shield'),
  ('Craiceann''s Carapace', 'Golden Plate'),
  ('The Surrender', 'Ezomyte Tower Shield'),
  ('Death''s Door', 'Crusader Boots'),
  ('Null and Void', 'Legion Gloves'),
  ('The Red Trail', 'Titan Greaves'),
  ('Fenumus'' Weave', 'Carnal Mitts'),
  ('The Unshattered Will', 'Archon Kite Shield'),
  ('Second Piece of Storms', 'Callous Mask Piece'),
  ('Aegis Aurora', 'Champion Kite Shield'),
  ('Slavedriver''s Hand', 'Ambush Mitts'),
  ('Windshriek', 'Reinforced Greaves'),
  ('The Vertex', 'Vaal Mask'),
  ('The Perfect Form', 'Zodiac Leather'),
  ('Lightpoacher', 'Great Crown'),
  ('Omeyocan', 'Carnal Boots'),
  ('Lycosidae', 'Rawhide Tower Shield'),
  ('Third Piece of Storms', 'Callous Mask Piece'),
  ('Tukohama''s Fortress', 'Ebony Tower Shield'),
  ('Esh''s Visage', 'Vaal Spirit Shield'),
  ('First Piece of Storms', 'Callous Mask Piece'),
  ('Magna Eclipsis', 'Pinnacle Tower Shield'),
  ('Voidfletcher', 'Penetrating Arrow Quiver'),
  ('Eber''s Unification', 'Hubris Circlet'),
  ('Farrul''s Bite', 'Harlequin Mask'),
  ('Frostferno', 'Leather Hood'),
  ('Mask of the Stitched Demon', 'Magistrate Crown'),
  ('Abberath''s Hooves', 'Goathide Boots'),
  ('Malachai''s Awakening', 'Iron Mask'),
  ('Bitterbind Point', 'Titanium Spirit Shield'),
  ('The Anticipation', 'Ezomyte Tower Shield'),
  ('Devoto''s Devotion', 'Nightmare Bascinet'),
  ('Inya''s Epiphany', 'Arcanist Slippers'),
  ('Volkuur''s Guidance', 'Zealot Gloves'),
  ('The Brass Dome', 'Gladiator Plate'),
  ('The Brine Crown', 'Prophet Crown'),
  ('Ylfeban''s Trickery', 'Hubris Circlet'),
  ('Third Piece of Focus', 'Archon Kite Shield Piece'),
  ('Fenumus'' Spinnerets', 'Assassin''s Boots'),
  ('Doryani''s Delusion', 'Sorcerer Boots'),
  ('The Iron Fortress', 'Crusader Plate'),
  ('The Snowblind Grace', 'Coronal Leather'),
  ('Vix Lunaris', 'Cardinal Round Shield'),
  ('Invictus Solaris', 'Archon Kite Shield'),
  ('Kintsugi', 'Exquisite Leather'),
  ('The Fracturing Spinner', 'Blunt Arrow Quiver'),
  ('Whakatutuki o Matua', 'Tarnished Spirit Shield'),
  ('Fourth Piece of Focus', 'Archon Kite Shield Piece'),
  ('Doedre''s Malevolence', 'Velvet Gloves'),
  ('First Piece of Focus', 'Archon Kite Shield Piece'),
  ('Hyrri''s Demise', 'Sharktooth Arrow Quiver'),
  ('Esh''s Mirror', 'Thorium Spirit Shield'),
  ('Second Piece of Focus', 'Archon Kite Shield Piece'),
  ('Shaper''s Touch', 'Crusader Gloves'),
  ('Sin Trek', 'Stealth Boots'),
  ('Winds of Change', 'Ancient Gauntlets'),
  ('Farrul''s Pounce', 'Hydrascale Gauntlets'),
  ('Grip of the Council', 'Arcanist Gloves'),
  ('Gruthkul''s Pelt', 'Wyrmscale Doublet'),
  ('Queen of the Forest', 'Destiny Leather'),
  ('Asenath''s Chant', 'Iron Circlet'),
  ('Carcass Jack', 'Varnished Coat'),
  ('Cloak of Defiance', 'Lacquered Garb'),
  ('Farrul''s Chase', 'Slink Boots'),
  ('Fenumus'' Toxins', 'Necromancer Circlet'),
  ('Geofri''s Legacy', 'Great Crown'),
  ('Hrimburn', 'Goathide Gloves'),
  ('The Formless Inferno', 'Royal Burgonet'),
  ('The Signal Fire', 'Fire Arrow Quiver'),
  ('Sunspite', 'Clasped Boots'),
  ('Belly of the Beast', 'Full Wyrmscale'),
  ('Cloak of Tawm''r Isley', 'Savant''s Robe'),
  ('Hale Negator', 'Mind Cage'),
  ('Indigon', 'Hubris Circlet'),
  ('The Gull', 'Raven Mask'),
  ('The Oak', 'Plank Kite Shield'),
  ('Death''s Oath', 'Astral Plate'),
  ('Deidbellow', 'Gilded Sallet'),
  ('Doryani''s Delusion', 'Titan Greaves'),
  ('Fox''s Fortune', 'Wild Leather'),
  ('Garukhan''s Flight', 'Stealth Boots'),
  ('Goldrim', 'Leather Cap'),
  ('Greedtrap', 'Velvet Slippers'),
  ('Hyrri''s Ire', 'Zodiac Leather'),
  ('Lioneye''s Remorse', 'Pinnacle Tower Shield'),
  ('Martyr''s Crown', 'Vine Circlet'),
  ('Rainbowstride', 'Conjurer Boots'),
  ('Second Piece of Directions', 'Blunt Arrow Quiver Piece'),
  ('Shavronne''s Gambit', 'Scholar Boots'),
  ('Third Piece of Directions', 'Blunt Arrow Quiver Piece'),
  ('Vixen''s Entrapment', 'Embroidered Gloves'),
  ('Yriel''s Fostering', 'Exquisite Leather'),
  ('Wall of Brambles', 'Plate Vest'),
  ('Allelopathy', 'Sorcerer Gloves'),
  ('Atziri''s Step', 'Slink Boots'),
  ('Aurseize', 'Steelscale Gauntlets'),
  ('Craiceann''s Chitin', 'Magistrate Crown'),
  ('Craiceann''s Pincers', 'Titan Gauntlets'),
  ('Craiceann''s Tracks', 'Goliath Greaves'),
  ('Daresso''s Defiance', 'Full Dragonscale'),
  ('Doryani''s Delusion', 'Slink Boots'),
  ('Drillneck', 'Penetrating Arrow Quiver'),
  ('First Piece of Directions', 'Blunt Arrow Quiver Piece'),
  ('Kaom''s Roots', 'Titan Greaves'),
  ('Memory Vault', 'Praetor Crown'),
  ('Obscurantis', 'Lion Pelt'),
  ('Prism Guardian', 'Archon Kite Shield'),
  ('Rathpith Globe', 'Titanium Spirit Shield'),
  ('Saqawal''s Nest', 'Blood Raiment'),
  ('Shadows and Dust', 'Clasped Mitts'),
  ('Soul Strike', 'Spike-Point Arrow Quiver'),
  ('Starkonja''s Head', 'Silken Hood'),
  ('Steppan Eard', 'Sorcerer Boots'),
  ('Unyielding Flame', 'Archon Kite Shield'),
  ('Voidwalker', 'Murder Boots'),
  ('Wildwrap', 'Strapped Leather'),
  ('Saqawal''s Flock', 'Silken Hood'),
  ('Apep''s Slumber', 'Ancient Spirit Shield'),
  ('Abyssus', 'Ezomyte Burgonet'),
  ('Alpha''s Howl', 'Sinner Tricorne'),
  ('Architect''s Hand', 'Strapped Mitts'),
  ('Brinerot Flag', 'Tarnished Spirit Shield'),
  ('Brinerot Whalers', 'Trapper Boots'),
  ('Broken Faith', 'Archon Kite Shield'),
  ('Cherrubim''s Maleficence', 'Triumphant Lamellar'),
  ('Cospri''s Will', 'Assassin''s Garb'),
  ('Cragfall', 'Serrated Arrow Quiver'),
  ('Crystal Vault', 'Latticed Ringmail'),
  ('Dance of the Offered', 'Shackled Boots'),
  ('Demon Stitcher', 'Satin Gloves'),
  ('Doedre''s Skin', 'Widowsilk Robe'),
  ('Doryani''s Fist', 'Vaal Gauntlets'),
  ('Duskblight', 'Ironscale Boots'),
  ('Ezomyte Hold', 'Iron Hat'),
  ('Flamesight', 'Solaris Circlet'),
  ('Flesh and Spirit', 'Ironscale Gauntlets'),
  ('Galesight', 'Solaris Circlet'),
  ('Geofri''s Sanctuary', 'Elegant Ringmail'),
  ('Haemophilia', 'Serpentscale Gauntlets'),
  ('Heretic''s Veil', 'Deicide Mask'),
  ('Incandescent Heart', 'Saintly Chainmail'),
  ('Kaltensoul', 'Painted Buckler'),
  ('Leper''s Alms', 'Mirrored Spiked Shield'),
  ('Lochtonial Caress', 'Iron Gauntlets'),
  ('Maligaro''s Virtuosity', 'Deerskin Gloves'),
  ('Mask of the Spirit Drinker', 'Crusader Helmet'),
  ('Mind of the Council', 'Harlequin Mask'),
  ('Rat''s Nest', 'Ursine Pelt'),
  ('Saffell''s Frame', 'Branded Kite Shield'),
  ('Saqawal''s Talons', 'Hydrascale Boots'),
  ('Saqawal''s Winds', 'Soldier Gloves'),
  ('Scold''s Bridle', 'Mind Cage'),
  ('Sentari''s Answer', 'Brass Spirit Shield'),
  ('Skirmish', 'Two-Point Arrow Quiver'),
  ('The Baron', 'Close Helmet'),
  ('The Beast Fur Shawl', 'Vaal Regalia'),
  ('The Coming Calamity', 'Destroyer Regalia'),
  ('The Formless Flame', 'Siege Helmet'),
  ('The Infinite Pursuit', 'Goliath Greaves'),
  ('Thirst for Horrors', 'War Buckler'),
  ('Thunderfist', 'Murder Mitts'),
  ('Thundersight', 'Solaris Circlet'),
  ('Tinkerskin', 'Sadist Garb'),
  ('Victario''s Charity', 'Laminated Kite Shield'),
  ('Victario''s Influence', 'Lacquered Garb'),
  ('Vis Mortis', 'Necromancer Silks'),
  ('Voidbringer', 'Conjurer Gloves'),
  ('Wanderlust', 'Wool Shoes'),
  ('Windscream', 'Reinforced Greaves'),
  ('Zeel''s Amplifier', 'Polished Spiked Shield'),
  ('The Rat Cage', 'Sharkskin Tunic'),
  ('Greed''s Embrace', 'Golden Plate'),
  ('Doedre''s Scorn', 'Lunaris Circlet'),
  ('Ahn''s Heritage', 'Colossal Tower Shield'),
  ('Atziri''s Mirror', 'Golden Buckler'),
  ('Blasphemer''s Grasp', 'Assassin''s Mitts'),
  ('Bloodbond', 'Bone Armour'),
  ('Chernobog''s Pillar', 'Ebony Tower Shield'),
  ('Crown of the Pale King', 'Regicide Mask'),
  ('Doedre''s Tenure', 'Velvet Gloves'),
  ('Empire''s Grasp', 'Goliath Gauntlets'),
  ('Facebreaker', 'Strapped Mitts'),
  ('Gorgon''s Gaze', 'Regicide Mask'),
  ('Great Old One''s Ward', 'Corrugated Buckler'),
  ('Leer Cast', 'Festival Mask'),
  ('Lightning Coil', 'Desert Brigandine'),
  ('Malachai''s Mark', 'Murder Mitts'),
  ('Maloney''s Nightfall', 'Blunt Arrow Quiver'),
  ('March of the Legion', 'Legion Boots'),
  ('Matua Tupuna', 'Tarnished Spirit Shield'),
  ('Meginord''s Vise', 'Steel Gauntlets'),
  ('Mutewind Whispersteps', 'Serpentscale Boots'),
  ('Oskarm', 'Nubuck Gloves'),
  ('Ralakesh''s Impatience', 'Riveted Boots'),
  ('Redblade Tramplers', 'Ancient Greaves'),
  ('Repentance', 'Crusader Gloves'),
  ('Rime Gaze', 'Mind Cage'),
  ('Rise of the Phoenix', 'Mosaic Kite Shield'),
  ('Sadima''s Touch', 'Wool Gloves'),
  ('Soul Mantle', 'Spidersilk Robe'),
  ('Southbound', 'Soldier Gloves'),
  ('Sundance', 'Clasped Boots'),
  ('The Blood Dance', 'Sharkskin Boots'),
  ('The Bringer of Rain', 'Nightmare Bascinet'),
  ('The Broken Crown', 'Prophet Crown'),
  ('The Peregrine', 'Visored Sallet'),
  ('The Restless Ward', 'Carnal Armour'),
  ('Titucius'' Span', 'Reinforced Tower Shield'),
  ('Trolltimber Spire', 'Cedar Tower Shield'),
  ('Vaal Caress', 'Bronzescale Gauntlets'),
  ('Voll''s Vision', 'Praetor Crown'),
  ('Worldcarver', 'Dragonscale Gauntlets'),
  ('Saemus'' Gift', 'Spike-Point Arrow Quiver'),
  ('The Covenant', 'Spidersilk Robe'),
  ('Viper''s Scales', 'Full Scale Armour'),
  ('Glitterdisc', 'Burnished Spiked Shield'),
  ('The Eternal Apple', 'Chiming Spirit Shield'),
  ('Alberon''s Warpath', 'Soldier Boots'),
  ('Kongming''s Stratagem', 'Ivory Spirit Shield'),
  ('Maligaro''s Lens', 'Compound Spiked Shield'),
  ('Skullhead', 'Secutor Helm'),
  ('Wraithlord', 'Bone Circlet'),
  ('Chitus'' Apex', 'Necromancer Circlet'),
  ('Giantsbane', 'Bronze Gauntlets'),
  ('Ahn''s Contempt', 'Praetor Crown'),
  ('Ambu''s Charge', 'Crusader Chainmail'),
  ('Asenath''s Gentle Touch', 'Silk Gloves'),
  ('Asenath''s Mark', 'Iron Circlet'),
  ('Black Sun Crest', 'Lacquered Helmet'),
  ('Briskwrap', 'Strapped Leather'),
  ('Bronn''s Lithe', 'Cutthroat''s Garb'),
  ('Chains of Command', 'Saintly Chainmail'),
  ('Cloak of Flame', 'Scholar''s Robe'),
  ('Crest of Perandus', 'Pine Buckler'),
  ('Crown of Eyes', 'Hubris Circlet'),
  ('Curtain Call', 'Plague Mask'),
  ('Daresso''s Courage', 'Baroque Round Shield'),
  ('Darkray Vectors', 'Dragonscale Boots'),
  ('Deerstalker', 'Deerskin Boots'),
  ('Dendrobate', 'Sentinel Jacket'),
  ('Gang''s Momentum', 'Legion Boots'),
  ('Geofri''s Crest', 'Great Crown'),
  ('Heatshiver', 'Leather Hood'),
  ('Hrimnor''s Resolve', 'Samite Helmet'),
  ('Hrimsorrow', 'Goathide Gloves'),
  ('Hyrri''s Bite', 'Sharktooth Arrow Quiver'),
  ('Icetomb', 'Latticed Ringmail'),
  ('Infernal Mantle', 'Widowsilk Robe'),
  ('Iron Heart', 'Crusader Plate'),
  ('Jaws of Agony', 'Supreme Spiked Shield'),
  ('Kalisa''s Grace', 'Samite Gloves'),
  ('Kingsguard', 'Conquest Chainmail'),
  ('Kitava''s Thirst', 'Zealot Helmet'),
  ('Lioneye''s Paws', 'Bronzescale Boots'),
  ('Lioneye''s Vision', 'Crusader Plate'),
  ('Malachai''s Loop', 'Harmonic Spirit Shield'),
  ('Malachai''s Simula', 'Iron Mask'),
  ('Mindspiral', 'Aventail Helmet'),
  ('Mutewind Pennant', 'Enameled Buckler'),
  ('Ondar''s Clasp', 'Wrapped Mitts'),
  ('Rearguard', 'Broadhead Arrow Quiver'),
  ('Redblade Banner', 'Painted Tower Shield'),
  ('Solaris Lorica', 'Copper Plate'),
  ('Stormcharger', 'Plated Greaves'),
  ('Surgebinders', 'Dragonscale Gauntlets'),
  ('The Embalmer', 'Carnal Mitts'),
  ('Three-step Assault', 'Shagreen Boots'),
  ('Victario''s Flight', 'Goathide Boots'),
  ('Voll''s Protector', 'Holy Chainmail'),
  ('Wyrmsign', 'Wyrmscale Gauntlets'),
  ('Zahndethus'' Cassock', 'Sage''s Robe'),
  ('Asphyxia''s Wrath', 'Two-Point Arrow Quiver'),
  ('Bramblejack', 'Plate Vest'),
  ('Crown of Thorns', 'Vine Circlet'),
  ('Deidbell', 'Gilded Sallet'),
  ('Foxshade', 'Wild Leather'),
  ('Mark of the Red Covenant', 'Tribal Circlet'),
  ('Nomic''s Storm', 'Strapped Boots'),
  ('Shackles of the Wretched', 'Chain Gloves'),
  ('Shavronne''s Pace', 'Scholar Boots'),
  ('Snakebite', 'Assassin''s Mitts'),
  ('Speaker''s Wreath', 'Prophet Crown'),
  ('Springleaf', 'Plank Kite Shield'),
  ('The Three Dragons', 'Golden Mask'),
  ('Thousand Teeth Temu', 'Vaal Buckler'),
  ('Wake of Destruction', 'Mesh Boots'),
  ('Bones of Ullr', 'Silk Slippers'),
  ('Dialla''s Malefaction', 'Sage''s Robe'),
  ('Veruso''s Battering Rams', 'Titan Gauntlets'),
  ('Veil of the Night', 'Great Helmet'),
  ('Slitherpinch', 'Bronzescale Gauntlets'),
  ('Ashrend', 'Buckskin Tunic'),
  ('Dusktoe', 'Ironscale Boots'),
  ('Chalice of Horrors', 'War Buckler'),
  ('Wondertrap', 'Velvet Slippers'),
  ('Blackgleam', 'Fire Arrow Quiver'),
  ('Craghead', 'Serrated Arrow Quiver'),
  ('Thousand Ribbons', 'Simple Robe'),
  ('Wheel of the Stormsail', 'Rotted Round Shield'),
  ('Ezomyte Peak', 'Iron Hat'),
  ('Fairgraves'' Tricorne', 'Tricorne'),
  ('Kaltenhalt', 'Painted Buckler'),
  ('Lightbane Raiment', 'Ornate Ringmail'),
  ('The Deep One''s Hide', 'Studded Round Shield'),
  ('Honourhome', 'Soldier Helmet'),
  ('Headhunter', 'Leather Belt'),
  ('Zerphi''s Heart', 'Paua Amulet'),
  ('The Pandemonius', 'Jade Amulet'),
  ('The Halcyon', 'Jade Amulet'),
  ('Xoph''s Blood', 'Amber Amulet'),
  ('Xoph''s Heart', 'Amber Amulet'),
  ('Solstice Vigil', 'Onyx Amulet'),
  ('Presence of Chayula', 'Onyx Amulet'),
  ('Yoke of Suffering', 'Onyx Amulet'),
  ('Mark of the Shaper', 'Opal Ring'),
  ('Aul''s Uprising', 'Onyx Amulet'),
  ('The Taming', 'Prismatic Ring'),
  ('Choir of the Storm', 'Lapis Amulet'),
  ('Impresence', 'Onyx Amulet'),
  ('Berek''s Respite', 'Two-Stone Ring'),
  ('Voice of the Storm', 'Lapis Amulet'),
  ('Voll''s Devotion', 'Agate Amulet'),
  ('Eyes of the Greatwolf', 'Greatwolf Talisman'),
  ('The Pariah', 'Unset Ring'),
  ('Bisco''s Collar', 'Gold Amulet'),
  ('Bisco''s Leash', 'Heavy Belt'),
  ('Ventor''s Gamble', 'Gold Ring'),
  ('Blightwell', 'Clutching Talisman'),
  ('Star of Wraeclast', 'Ruby Amulet'),
  ('Natural Hierarchy', 'Rotfeather Talisman'),
  ('Coward''s Legacy', 'Chain Belt'),
  ('Precursor''s Emblem', 'Prismatic Ring'),
  ('Shavronne''s Revelation', 'Moonstone Ring'),
  ('Kaom''s Way', 'Coral Ring'),
  ('Rigwald''s Curse', 'Wereclaw Talisman'),
  ('Astramentis', 'Onyx Amulet'),
  ('The Flow Untethered', 'Cloth Belt'),
  ('Valako''s Sign', 'Topaz Ring'),
  ('Putembo''s Meadow', 'Topaz Ring'),
  ('The Primordial Chain', 'Coral Amulet'),
  ('Eye of Innocence', 'Citrine Amulet'),
  ('Precursor''s Emblem', 'Two-Stone Ring'),
  ('Gifts from Above', 'Diamond Ring'),
  ('The Ascetic', 'Gold Amulet'),
  ('Uzaza''s Mountain', 'Sapphire Ring'),
  ('Berek''s Grip', 'Two-Stone Ring'),
  ('Hinekora''s Sight', 'Onyx Amulet'),
  ('Thief''s Torment', 'Prismatic Ring'),
  ('Vivinsect', 'Unset Ring'),
  ('Ahkeli''s Valley', 'Ruby Ring'),
  ('The Tactician', 'Studded Belt'),
  ('Call of the Brotherhood', 'Two-Stone Ring'),
  ('Essence Worm', 'Unset Ring'),
  ('The Retch', 'Rustic Sash'),
  ('Ascent From Flesh', 'Chain Belt'),
  ('The Nomad', 'Studded Belt'),
  ('Timetwist', 'Moonstone Ring'),
  ('First Piece of Time', 'Cloth Belt Piece'),
  ('Karui Charge', 'Jade Amulet'),
  ('The Effigon', 'Gold Amulet'),
  ('Second Piece of Time', 'Cloth Belt Piece'),
  ('Hyperboreus', 'Leather Belt'),
  ('Le Heup of All', 'Iron Ring'),
  ('Mark of the Elder', 'Steel Ring'),
  ('Perandus Signet', 'Paua Ring'),
  ('Snakepit', 'Sapphire Ring'),
  ('Dream Fragments', 'Sapphire Ring'),
  ('Mark of Submission', 'Unset Ring'),
  ('Rigwald''s Crest', 'Two-Stone Ring'),
  ('Voidheart', 'Iron Ring'),
  ('Winterweave', 'Coral Ring'),
  ('Ahkeli''s Mountain', 'Ruby Ring'),
  ('Berek''s Pass', 'Two-Stone Ring'),
  ('Blood of Corruption', 'Amber Amulet'),
  ('Brinerot Mark', 'Unset Ring'),
  ('Doedre''s Damning', 'Paua Ring'),
  ('Faminebind', 'Rustic Sash'),
  ('Gloomfang', 'Blue Pearl Amulet'),
  ('Ngamahu Tiki', 'Coral Amulet'),
  ('Ngamahu''s Sign', 'Ruby Ring'),
  ('Night''s Hold', 'Black Maw Talisman'),
  ('Putembo''s Valley', 'Topaz Ring'),
  ('Pyre', 'Sapphire Ring'),
  ('Redblade Band', 'Unset Ring'),
  ('Stormfire', 'Opal Ring'),
  ('Tasalio''s Sign', 'Sapphire Ring'),
  ('Uzaza''s Meadow', 'Sapphire Ring'),
  ('Voideye', 'Unset Ring'),
  ('Auxium', 'Crystal Belt'),
  ('Death Rush', 'Amethyst Ring'),
  ('Emberwake', 'Ruby Ring'),
  ('Ming''s Heart', 'Amethyst Ring'),
  ('Mutewind Seal', 'Unset Ring'),
  ('Romira''s Banquet', 'Diamond Ring'),
  ('The Hungry Loop', 'Unset Ring'),
  ('Valyrium', 'Moonstone Ring'),
  ('Malachai''s Artifice', 'Unset Ring'),
  ('Heartbound Loop', 'Moonstone Ring'),
  ('Lori''s Lantern', 'Prismatic Ring'),
  ('The Warden''s Brand', 'Iron Ring'),
  ('Umbilicus Immortalis', 'Leather Belt'),
  ('Andvarius', 'Gold Ring'),
  ('Atziri''s Foible', 'Paua Amulet'),
  ('Bated Breath', 'Chain Belt'),
  ('Blackheart', 'Iron Ring'),
  ('Bloodboil', 'Coral Ring'),
  ('Bloodgrip', 'Marble Amulet'),
  ('Carnage Heart', 'Onyx Amulet'),
  ('Coward''s Chains', 'Chain Belt'),
  ('Cyclopean Coil', 'Leather Belt'),
  ('Daresso''s Salute', 'Citrine Amulet'),
  ('Darkness Enthroned', 'Stygian Vise'),
  ('Doryani''s Invitation', 'Heavy Belt'),
  ('Eye of Chayula', 'Onyx Amulet'),
  ('Feastbind', 'Rustic Sash'),
  ('Gluttony', 'Leather Belt'),
  ('Kaom''s Sign', 'Coral Ring'),
  ('Karui Ward', 'Jade Amulet'),
  ('Kikazaru', 'Topaz Ring'),
  ('Mokou''s Embrace', 'Ruby Ring'),
  ('Praxis', 'Paua Ring'),
  ('Ryslatha''s Coil', 'Studded Belt'),
  ('Sacrificial Heart', 'Paua Amulet'),
  ('Sibyl''s Lament', 'Coral Ring'),
  ('Timeclasp', 'Moonstone Ring'),
  ('Victario''s Acuity', 'Turquoise Amulet'),
  ('Belt of the Deceiver', 'Heavy Belt'),
  ('Dyadian Dawn', 'Heavy Belt'),
  ('Extractor Mentis', 'Agate Amulet'),
  ('Hyrri''s Truth', 'Jade Amulet'),
  ('Marylene''s Fallacy', 'Lapis Amulet'),
  ('Meginord''s Girdle', 'Heavy Belt'),
  ('Perandus Blazon', 'Cloth Belt'),
  ('Perquil''s Toe', 'Gold Amulet'),
  ('Perseverance', 'Vanguard Belt'),
  ('Soulthirst', 'Cloth Belt'),
  ('String of Servitude', 'Heavy Belt'),
  ('The Anvil', 'Amber Amulet'),
  ('Warped Timepiece', 'Turquoise Amulet'),
  ('The Magnate', 'Studded Belt'),
  ('The Aylardex', 'Agate Amulet'),
  ('Rashkaldor''s Patience', 'Jade Amulet'),
  ('Araku Tiki', 'Coral Amulet'),
  ('Immortal Flesh', 'Leather Belt'),
  ('Maligaro''s Cruelty', 'Turquoise Amulet'),
  ('Maligaro''s Restraint', 'Chain Belt'),
  ('Prismweave', 'Rustic Sash'),
  ('Shaper''s Seed', 'Agate Amulet'),
  ('Soul Tether', 'Cloth Belt'),
  ('Stone of Lazhwar', 'Lapis Amulet'),
  ('Sunblast', 'Cloth Belt'),
  ('Tear of Purity', 'Lapis Amulet'),
  ('Winterheart', 'Gold Amulet'),
  ('Wurm''s Molt', 'Leather Belt'),
  ('Sidhebreath', 'Paua Amulet'),
  ('Ungil''s Harmony', 'Turquoise Amulet'),
  ('The Ignomon', 'Gold Amulet'),
  ('Cragfall', 'Serrated Arrow Quiver'),
  ('Crystal Vault', 'Latticed Ringmail'),
  ('Dance of the Offered', 'Shackled Boots'),
  ('Demon Stitcher', 'Satin Gloves'),
  ('Doedre''s Skin', 'Widowsilk Robe'),
  ('Doryani''s Fist', 'Vaal Gauntlets'),
  ('Duskblight', 'Ironscale Boots'),
  ('Ezomyte Hold', 'Iron Hat'),
  ('Flamesight', 'Solaris Circlet'),
  ('Flesh and Spirit', 'Ironscale Gauntlets'),
  ('Galesight', 'Solaris Circlet'),
  ('Geofri''s Sanctuary', 'Elegant Ringmail'),
  ('Haemophilia', 'Serpentscale Gauntlets'),
  ('Heretic''s Veil', 'Deicide Mask'),
  ('Incandescent Heart', 'Saintly Chainmail'),
  ('Kaltensoul', 'Painted Buckler'),
  ('Leper''s Alms', 'Mirrored Spiked Shield'),
  ('Lochtonial Caress', 'Iron Gauntlets'),
  ('Maligaro''s Virtuosity', 'Deerskin Gloves'),
  ('Mask of the Spirit Drinker', 'Crusader Helmet'),
  ('Mind of the Council', 'Harlequin Mask'),
  ('Rat''s Nest', 'Ursine Pelt'),
  ('Saffell''s Frame', 'Branded Kite Shield'),
  ('Saqawal''s Talons', 'Hydrascale Boots'),
  ('Saqawal''s Winds', 'Soldier Gloves'),
  ('Scold''s Bridle', 'Mind Cage'),
  ('Sentari''s Answer', 'Brass Spirit Shield'),
  ('Skirmish', 'Two-Point Arrow Quiver'),
  ('The Baron', 'Close Helmet'),
  ('The Beast Fur Shawl', 'Vaal Regalia'),
  ('The Coming Calamity', 'Destroyer Regalia'),
  ('The Formless Flame', 'Siege Helmet'),
  ('The Infinite Pursuit', 'Goliath Greaves'),
  ('Thirst for Horrors', 'War Buckler'),
  ('Thunderfist', 'Murder Mitts'),
  ('Thundersight', 'Solaris Circlet'),
  ('Tinkerskin', 'Sadist Garb'),
  ('Tombfist', 'Steelscale Gauntlets'),
  ('Victario''s Charity', 'Laminated Kite Shield'),
  ('Victario''s Influence', 'Lacquered Garb'),
  ('Vis Mortis', 'Necromancer Silks'),
  ('Voidbringer', 'Conjurer Gloves'),
  ('Wanderlust', 'Wool Shoes'),
  ('Windscream', 'Reinforced Greaves'),
  ('Zeel''s Amplifier', 'Polished Spiked Shield'),
  ('The Rat Cage', 'Sharkskin Tunic'),
  ('Greed''s Embrace', 'Golden Plate'),
  ('Doedre''s Scorn', 'Lunaris Circlet'),
  ('Ahn''s Heritage', 'Colossal Tower Shield'),
  ('Atziri''s Mirror', 'Golden Buckler'),
  ('Blasphemer''s Grasp', 'Assassin''s Mitts'),
  ('Bloodbond', 'Bone Armour'),
  ('Chernobog''s Pillar', 'Ebony Tower Shield'),
  ('Crown of the Pale King', 'Regicide Mask'),
  ('Doedre''s Tenure', 'Velvet Gloves'),
  ('Empire''s Grasp', 'Goliath Gauntlets'),
  ('Facebreaker', 'Strapped Mitts'),
  ('Gorgon''s Gaze', 'Regicide Mask'),
  ('Great Old One''s Ward', 'Corrugated Buckler'),
  ('Leer Cast', 'Festival Mask'),
  ('Lightning Coil', 'Desert Brigandine'),
  ('Lightpoacher', 'Great Crown'),
  ('Malachai''s Mark', 'Murder Mitts'),
  ('Maloney''s Nightfall', 'Blunt Arrow Quiver'),
  ('March of the Legion', 'Legion Boots'),
  ('Matua Tupuna', 'Tarnished Spirit Shield'),
  ('Meginord''s Vise', 'Steel Gauntlets'),
  ('Mutewind Whispersteps', 'Serpentscale Boots'),
  ('Oskarm', 'Nubuck Gloves'),
  ('Ralakesh''s Impatience', 'Riveted Boots'),
  ('Redblade Tramplers', 'Ancient Greaves'),
  ('Repentance', 'Crusader Gloves'),
  ('Rime Gaze', 'Mind Cage'),
  ('Rise of the Phoenix', 'Mosaic Kite Shield'),
  ('Sadima''s Touch', 'Wool Gloves'),
  ('Soul Mantle', 'Spidersilk Robe'),
  ('Southbound', 'Soldier Gloves'),
  ('Sundance', 'Clasped Boots'),
  ('The Blood Dance', 'Sharkskin Boots'),
  ('The Bringer of Rain', 'Nightmare Bascinet'),
  ('The Broken Crown', 'Prophet Crown'),
  ('The Peregrine', 'Visored Sallet'),
  ('The Restless Ward', 'Carnal Armour'),
  ('Titucius'' Span', 'Reinforced Tower Shield'),
  ('Trolltimber Spire', 'Cedar Tower Shield'),
  ('Vaal Caress', 'Bronzescale Gauntlets'),
  ('Voll''s Vision', 'Praetor Crown'),
  ('Worldcarver', 'Dragonscale Gauntlets'),
  ('Saemus'' Gift', 'Spike-Point Arrow Quiver'),
  ('The Covenant', 'Spidersilk Robe'),
  ('Viper''s Scales', 'Full Scale Armour'),
  ('Glitterdisc', 'Burnished Spiked Shield'),
  ('The Eternal Apple', 'Chiming Spirit Shield'),
  ('Alberon''s Warpath', 'Soldier Boots'),
  ('Kongming''s Stratagem', 'Ivory Spirit Shield'),
  ('Maligaro''s Lens', 'Compound Spiked Shield'),
  ('Skullhead', 'Secutor Helm'),
  ('Wraithlord', 'Bone Circlet'),
  ('Chitus'' Apex', 'Necromancer Circlet'),
  ('Giantsbane', 'Bronze Gauntlets'),
  ('Ahn''s Contempt', 'Praetor Crown'),
  ('Ambu''s Charge', 'Crusader Chainmail'),
  ('Asenath''s Gentle Touch', 'Silk Gloves'),
  ('Asenath''s Mark', 'Iron Circlet'),
  ('Black Sun Crest', 'Lacquered Helmet'),
  ('Briskwrap', 'Strapped Leather'),
  ('Bronn''s Lithe', 'Cutthroat''s Garb'),
  ('Chains of Command', 'Saintly Chainmail'),
  ('Cloak of Flame', 'Scholar''s Robe'),
  ('Crest of Perandus', 'Pine Buckler'),
  ('Crown of Eyes', 'Hubris Circlet'),
  ('Curtain Call', 'Plague Mask'),
  ('Daresso''s Courage', 'Baroque Round Shield'),
  ('Darkray Vectors', 'Dragonscale Boots'),
  ('Deerstalker', 'Deerskin Boots'),
  ('Dendrobate', 'Sentinel Jacket'),
  ('Gang''s Momentum', 'Legion Boots'),
  ('Geofri''s Crest', 'Great Crown'),
  ('Heatshiver', 'Leather Hood'),
  ('Hrimnor''s Resolve', 'Samite Helmet'),
  ('Hrimsorrow', 'Goathide Gloves'),
  ('Hyrri''s Bite', 'Sharktooth Arrow Quiver'),
  ('Icetomb', 'Latticed Ringmail'),
  ('Infernal Mantle', 'Widowsilk Robe'),
  ('Iron Heart', 'Crusader Plate'),
  ('Jaws of Agony', 'Supreme Spiked Shield'),
  ('Kalisa''s Grace', 'Samite Gloves'),
  ('Kingsguard', 'Conquest Chainmail'),
  ('Kitava''s Thirst', 'Zealot Helmet'),
  ('Lioneye''s Paws', 'Bronzescale Boots'),
  ('Lioneye''s Vision', 'Crusader Plate'),
  ('Malachai''s Loop', 'Harmonic Spirit Shield'),
  ('Malachai''s Simula', 'Iron Mask'),
  ('Mindspiral', 'Aventail Helmet'),
  ('Mutewind Pennant', 'Enameled Buckler'),
  ('Ondar''s Clasp', 'Wrapped Mitts'),
  ('Rearguard', 'Broadhead Arrow Quiver'),
  ('Redblade Banner', 'Painted Tower Shield'),
  ('Solaris Lorica', 'Copper Plate'),
  ('Stormcharger', 'Plated Greaves'),
  ('Surgebinders', 'Dragonscale Gauntlets'),
  ('The Embalmer', 'Carnal Mitts'),
  ('Three-step Assault', 'Shagreen Boots'),
  ('Victario''s Flight', 'Goathide Boots'),
  ('Voll''s Protector', 'Holy Chainmail'),
  ('Wyrmsign', 'Wyrmscale Gauntlets'),
  ('Zahndethus'' Cassock', 'Sage''s Robe'),
  ('Asphyxia''s Wrath', 'Two-Point Arrow Quiver'),
  ('Bramblejack', 'Plate Vest'),
  ('Crown of Thorns', 'Vine Circlet'),
  ('Deidbell', 'Gilded Sallet'),
  ('Foxshade', 'Wild Leather'),
  ('Mark of the Red Covenant', 'Tribal Circlet'),
  ('Nomic''s Storm', 'Strapped Boots'),
  ('Shackles of the Wretched', 'Chain Gloves'),
  ('Shavronne''s Pace', 'Scholar Boots'),
  ('Snakebite', 'Assassin''s Mitts'),
  ('Speaker''s Wreath', 'Prophet Crown'),
  ('Springleaf', 'Plank Kite Shield'),
  ('The Three Dragons', 'Golden Mask'),
  ('Thousand Teeth Temu', 'Vaal Buckler'),
  ('Wake of Destruction', 'Mesh Boots'),
  ('Bones of Ullr', 'Silk Slippers'),
  ('Dialla''s Malefaction', 'Sage''s Robe'),
  ('Veruso''s Battering Rams', 'Titan Gauntlets'),
  ('Veil of the Night', 'Great Helmet'),
  ('Slitherpinch', 'Bronzescale Gauntlets'),
  ('Ashrend', 'Buckskin Tunic'),
  ('Dusktoe', 'Ironscale Boots'),
  ('Chalice of Horrors', 'War Buckler'),
  ('Wondertrap', 'Velvet Slippers'),
  ('Blackgleam', 'Fire Arrow Quiver'),
  ('Craghead', 'Serrated Arrow Quiver'),
  ('Thousand Ribbons', 'Simple Robe'),
  ('Wheel of the Stormsail', 'Rotted Round Shield'),
  ('Ezomyte Peak', 'Iron Hat'),
  ('Fairgraves'' Tricorne', 'Tricorne'),
  ('Kaltenhalt', 'Painted Buckler'),
  ('Lightbane Raiment', 'Ornate Ringmail'),
  ('The Deep One''s Hide', 'Studded Round Shield'),
  ('Honourhome', 'Soldier Helmet'),
  ('Unnatural Instinct', 'Viridian Jewel'),
  ('The Green Nightmare', 'Viridian Jewel'),
  ('The Green Dream', 'Viridian Jewel'),
  ('The Red Nightmare', 'Crimson Jewel'),
  ('Inspired Learning', 'Crimson Jewel'),
  ('Energy From Within', 'Cobalt Jewel'),
  ('The Red Dream', 'Crimson Jewel'),
  ('Might of the Meek', 'Crimson Jewel'),
  ('Watcher''s Eye', 'Prismatic Jewel'),
  ('Transcendent Spirit', 'Viridian Jewel'),
  ('The Anima Stone', 'Prismatic Jewel'),
  ('Transcendent Mind', 'Cobalt Jewel'),
  ('Transcendent Flesh', 'Crimson Jewel'),
  ('Intuitive Leap', 'Viridian Jewel'),
  ('Lioneye''s Fall', 'Viridian Jewel'),
  ('The Blue Dream', 'Cobalt Jewel'),
  ('Primordial Harmony', 'Cobalt Jewel'),
  ('Primordial Might', 'Crimson Jewel'),
  ('Clear Mind', 'Cobalt Jewel'),
  ('Grand Spectrum', 'Cobalt Jewel'),
  ('Fragility', 'Crimson Jewel'),
  ('Grand Spectrum', 'Viridian Jewel'),
  ('Primordial Eminence', 'Viridian Jewel'),
  ('Pure Talent', 'Viridian Jewel'),
  ('Unending Hunger', 'Cobalt Jewel'),
  ('Anatomical Knowledge', 'Cobalt Jewel'),
  ('Brute Force Solution', 'Cobalt Jewel'),
  ('Chill of Corruption', 'Viridian Jewel'),
  ('Combat Focus', 'Crimson Jewel'),
  ('Combat Focus', 'Viridian Jewel'),
  ('Conqueror''s Potency', 'Cobalt Jewel'),
  ('Corrupted Energy', 'Cobalt Jewel'),
  ('Dead Reckoning', 'Cobalt Jewel'),
  ('Efficient Training', 'Crimson Jewel'),
  ('Fertile Mind', 'Cobalt Jewel'),
  ('Fevered Mind', 'Cobalt Jewel'),
  ('Fireborn', 'Crimson Jewel'),
  ('First Snow', 'Cobalt Jewel'),
  ('From Dust', 'Cobalt Jewel'),
  ('Frozen Trail', 'Cobalt Jewel'),
  ('Hungry Abyss', 'Viridian Jewel'),
  ('Izaro''s Turmoil', 'Crimson Jewel'),
  ('Sacrificial Harvest', 'Viridian Jewel'),
  ('Self-Flagellation', 'Viridian Jewel'),
  ('Spreading Rot', 'Cobalt Jewel'),
  ('The Golden Rule', 'Viridian Jewel'),
  ('The Long Winter', 'Cobalt Jewel'),
  ('The Vigil', 'Crimson Jewel'),
  ('To Dust', 'Cobalt Jewel'),
  ('Vaal Sentencing', 'Cobalt Jewel'),
  ('Grand Spectrum', 'Crimson Jewel'),
  ('Careful Planning', 'Viridian Jewel'),
  ('Ancient Waystones', 'Crimson Jewel'),
  ('Apparitions', 'Viridian Jewel'),
  ('Assassin''s Haste', 'Cobalt Jewel'),
  ('Atziri''s Reign', 'Crimson Jewel'),
  ('Blood Sacrifice', 'Crimson Jewel'),
  ('Brawn', 'Crimson Jewel'),
  ('Coated Shrapnel', 'Crimson Jewel'),
  ('Collateral Damage', 'Viridian Jewel'),
  ('Combat Focus', 'Cobalt Jewel'),
  ('Combustibles', 'Crimson Jewel'),
  ('Conqueror''s Efficiency', 'Crimson Jewel'),
  ('Eldritch Knowledge', 'Cobalt Jewel'),
  ('Energised Armour', 'Crimson Jewel'),
  ('Fight for Survival', 'Viridian Jewel'),
  ('Fluid Motion', 'Viridian Jewel'),
  ('Fortified Legion', 'Cobalt Jewel'),
  ('Growing Agony', 'Viridian Jewel'),
  ('Hair Trigger', 'Viridian Jewel'),
  ('Hazardous Research', 'Cobalt Jewel'),
  ('Healthy Mind', 'Cobalt Jewel'),
  ('Hidden Potential', 'Viridian Jewel'),
  ('Hotfooted', 'Viridian Jewel'),
  ('Inertia', 'Crimson Jewel'),
  ('Inevitability', 'Cobalt Jewel'),
  ('Malicious Intent', 'Cobalt Jewel'),
  ('Martial Artistry', 'Crimson Jewel'),
  ('Mutated Growth', 'Cobalt Jewel'),
  ('Omen on the Winds', 'Viridian Jewel'),
  ('Powerlessness', 'Cobalt Jewel'),
  ('Pugilist', 'Viridian Jewel'),
  ('Rain of Splinters', 'Crimson Jewel'),
  ('Rapid Expansion', 'Crimson Jewel'),
  ('Reckless Defence', 'Cobalt Jewel'),
  ('Ring of Blades', 'Viridian Jewel'),
  ('Rolling Flames', 'Cobalt Jewel'),
  ('Soul''s Wick', 'Cobalt Jewel'),
  ('Spire of Stone', 'Crimson Jewel'),
  ('Spirit Guards', 'Viridian Jewel'),
  ('Spirited Response', 'Cobalt Jewel'),
  ('Static Electricity', 'Viridian Jewel'),
  ('Steel Spirit', 'Viridian Jewel'),
  ('Tempered Mind', 'Cobalt Jewel'),
  ('Tempered Spirit', 'Viridian Jewel'),
  ('Violent Dead', 'Cobalt Jewel'),
  ('Volley Fire', 'Viridian Jewel'),
  ('Weight of Sin', 'Viridian Jewel'),
  ('Wildfire', 'Crimson Jewel'),
  ('Mantra of Flames', 'Crimson Jewel'),
  ('Might and Influence', 'Viridian Jewel'),
  ('Overwhelming Odds', 'Crimson Jewel'),
  ('Pitch Darkness', 'Viridian Jewel'),
  ('Sudden Ignition', 'Viridian Jewel'),
  ('Tempered Flesh', 'Crimson Jewel'),
  ('Winter Burial', 'Crimson Jewel'),
  ('Winter''s Bounty', 'Cobalt Jewel'),
  ('Cold Steel', 'Viridian Jewel'),
  ('Fragile Bloom', 'Crimson Jewel'),
  ('Brittle Barrier', 'Cobalt Jewel'),
  ('Cheap Construction', 'Viridian Jewel'),
  ('Conqueror''s Longevity', 'Viridian Jewel'),
  ('Might in All Forms', 'Crimson Jewel'),
  ('Pacifism', 'Viridian Jewel'),
  ('Poacher''s Aim', 'Viridian Jewel'),
  ('Shattered Chains', 'Crimson Jewel'),
  ('Survival Instincts', 'Viridian Jewel'),
  ('Survival Skills', 'Crimson Jewel'),
  ('Unstable Payload', 'Cobalt Jewel'),
  ('Warlord''s Reach', 'Crimson Jewel'),
  ('Weight of the Empire', 'Crimson Jewel'),
  ('Survival Secrets', 'Cobalt Jewel');