INSERT INTO uniques (name, base)
  VALUES
  ('Soul Ripper', 'Quartz Flask'),
  ('Bottled Faith', 'Sulphur Flask'),
  ('Dying Sun', 'Ruby Flask'),
  ('Cinderswallow Urn', 'Silver Flask'),
  ('Taste of Hate', 'Sapphire Flask'),
  ('Sin''s Rebirth', 'Stibnite Flask'),
  ('Vessel of Vinktar', 'Topaz Flask'),
  ('Zerphi''s Last Breath', 'Grand Mana Flask'),
  ('The Wise Oak', 'Bismuth Flask'),
  ('Blood of the Karui', 'Sanctified Life Flask'),
  ('Coruscating Elixir', 'Ruby Flask'),
  ('Witchfire Brew', 'Stibnite Flask'),
  ('Lavianga''s Spirit', 'Sanctified Mana Flask'),
  ('Lion''s Roar', 'Granite Flask'),
  ('Rumi''s Concoction', 'Granite Flask'),
  ('Atziri''s Promise', 'Amethyst Flask'),
  ('Divination Distillate', 'Large Hybrid Flask'),
  ('The Writhing Jar', 'Hallowed Hybrid Flask'),
  ('Coralito''s Signature', 'Diamond Flask'),
  ('Forbidden Taste', 'Quartz Flask'),
  ('Kiara''s Determination', 'Silver Flask'),
  ('Rotgut', 'Quicksilver Flask'),
  ('Soul Catcher', 'Quartz Flask'),
  ('The Overflowing Chalice', 'Sulphur Flask'),
  ('Doedre''s Elixir', 'Greater Mana Flask'),
  ('The Sorrow of the Divine', 'Sulphur Flask');