INSERT INTO uniques (name, base)
  VALUES
  ('Atziri''s Reflection', 'Golden Buckler'),
  ('Farrul''s Fur', 'Triumphant Lamellar'),
  ('The Devouring Diadem', 'Necromancer Circlet'),
  ('The Queen''s Hunger', 'Vaal Regalia'),
  ('Skyforth', 'Sorcerer Boots'),
  ('Inpulsa''s Broken Heart', 'Sadist Garb'),
  ('Shavronne''s Wrappings', 'Occultist''s Vestment'),
  ('Rigwald''s Quills', 'Two-Point Arrow Quiver'),
  ('Apep''s Supremacy', 'Vaal Spirit Shield'),
  ('The Eternity Shroud', 'Blood Raiment'),
  ('Seven-League Step', 'Rawhide Boots'),
  ('Atziri''s Acuity', 'Vaal Gauntlets'),
  ('Command of the Pit', 'Riveted Gloves'),
  ('Kaom''s Heart', 'Glorious Plate'),
  ('Goldwyrm', 'Nubuck Boots'),
  ('Bubonic Trail', 'Murder Boots'),
  ('Tombfist', 'Steelscale Gauntlets'),
  ('Loreweave', 'Elegant Ringmail'),
  ('The Tempest''s Binding', 'Callous Mask'),
  ('Fenumus'' Shroud', 'Widowsilk Robe'),
  ('Shroud of the Lightless', 'Carnal Armour'),
  ('Atziri''s Splendour', 'Sacrificial Garb'),
  ('Light of Lunaris', 'Jingling Spirit Shield'),
  ('Craiceann''s Carapace', 'Golden Plate'),
  ('The Surrender', 'Ezomyte Tower Shield'),
  ('Death''s Door', 'Crusader Boots'),
  ('Null and Void', 'Legion Gloves'),
  ('The Red Trail', 'Titan Greaves'),
  ('Fenumus'' Weave', 'Carnal Mitts'),
  ('The Unshattered Will', 'Archon Kite Shield'),
  ('Second Piece of Storms', 'Callous Mask Piece'),
  ('Aegis Aurora', 'Champion Kite Shield'),
  ('Slavedriver''s Hand', 'Ambush Mitts'),
  ('Windshriek', 'Reinforced Greaves'),
  ('The Vertex', 'Vaal Mask'),
  ('The Perfect Form', 'Zodiac Leather'),
  ('Lightpoacher', 'Great Crown'),
  ('Omeyocan', 'Carnal Boots'),
  ('Lycosidae', 'Rawhide Tower Shield'),
  ('Third Piece of Storms', 'Callous Mask Piece'),
  ('Tukohama''s Fortress', 'Ebony Tower Shield'),
  ('Esh''s Visage', 'Vaal Spirit Shield'),
  ('First Piece of Storms', 'Callous Mask Piece'),
  ('Magna Eclipsis', 'Pinnacle Tower Shield'),
  ('Voidfletcher', 'Penetrating Arrow Quiver'),
  ('Eber''s Unification', 'Hubris Circlet'),
  ('Farrul''s Bite', 'Harlequin Mask'),
  ('Frostferno', 'Leather Hood'),
  ('Mask of the Stitched Demon', 'Magistrate Crown'),
  ('Abberath''s Hooves', 'Goathide Boots'),
  ('Malachai''s Awakening', 'Iron Mask'),
  ('Bitterbind Point', 'Titanium Spirit Shield'),
  ('The Anticipation', 'Ezomyte Tower Shield'),
  ('Devoto''s Devotion', 'Nightmare Bascinet'),
  ('Inya''s Epiphany', 'Arcanist Slippers'),
  ('Volkuur''s Guidance', 'Zealot Gloves'),
  ('The Brass Dome', 'Gladiator Plate'),
  ('The Brine Crown', 'Prophet Crown'),
  ('Ylfeban''s Trickery', 'Hubris Circlet'),
  ('Third Piece of Focus', 'Archon Kite Shield Piece'),
  ('Fenumus'' Spinnerets', 'Assassin''s Boots'),
  ('Doryani''s Delusion', 'Sorcerer Boots'),
  ('The Iron Fortress', 'Crusader Plate'),
  ('The Snowblind Grace', 'Coronal Leather'),
  ('Vix Lunaris', 'Cardinal Round Shield'),
  ('Invictus Solaris', 'Archon Kite Shield'),
  ('Kintsugi', 'Exquisite Leather'),
  ('The Fracturing Spinner', 'Blunt Arrow Quiver'),
  ('Whakatutuki o Matua', 'Tarnished Spirit Shield'),
  ('Fourth Piece of Focus', 'Archon Kite Shield Piece'),
  ('Doedre''s Malevolence', 'Velvet Gloves'),
  ('First Piece of Focus', 'Archon Kite Shield Piece'),
  ('Hyrri''s Demise', 'Sharktooth Arrow Quiver'),
  ('Esh''s Mirror', 'Thorium Spirit Shield'),
  ('Second Piece of Focus', 'Archon Kite Shield Piece'),
  ('Shaper''s Touch', 'Crusader Gloves'),
  ('Sin Trek', 'Stealth Boots'),
  ('Winds of Change', 'Ancient Gauntlets'),
  ('Farrul''s Pounce', 'Hydrascale Gauntlets'),
  ('Grip of the Council', 'Arcanist Gloves'),
  ('Gruthkul''s Pelt', 'Wyrmscale Doublet'),
  ('Queen of the Forest', 'Destiny Leather'),
  ('Asenath''s Chant', 'Iron Circlet'),
  ('Carcass Jack', 'Varnished Coat'),
  ('Cloak of Defiance', 'Lacquered Garb'),
  ('Farrul''s Chase', 'Slink Boots'),
  ('Fenumus'' Toxins', 'Necromancer Circlet'),
  ('Geofri''s Legacy', 'Great Crown'),
  ('Hrimburn', 'Goathide Gloves'),
  ('The Formless Inferno', 'Royal Burgonet'),
  ('The Signal Fire', 'Fire Arrow Quiver'),
  ('Sunspite', 'Clasped Boots'),
  ('Belly of the Beast', 'Full Wyrmscale'),
  ('Cloak of Tawm''r Isley', 'Savant''s Robe'),
  ('Hale Negator', 'Mind Cage'),
  ('Indigon', 'Hubris Circlet'),
  ('The Gull', 'Raven Mask'),
  ('The Oak', 'Plank Kite Shield'),
  ('Death''s Oath', 'Astral Plate'),
  ('Deidbellow', 'Gilded Sallet'),
  ('Doryani''s Delusion', 'Titan Greaves'),
  ('Fox''s Fortune', 'Wild Leather'),
  ('Garukhan''s Flight', 'Stealth Boots'),
  ('Goldrim', 'Leather Cap'),
  ('Greedtrap', 'Velvet Slippers'),
  ('Hyrri''s Ire', 'Zodiac Leather'),
  ('Lioneye''s Remorse', 'Pinnacle Tower Shield'),
  ('Martyr''s Crown', 'Vine Circlet'),
  ('Rainbowstride', 'Conjurer Boots'),
  ('Second Piece of Directions', 'Blunt Arrow Quiver Piece'),
  ('Shavronne''s Gambit', 'Scholar Boots'),
  ('Third Piece of Directions', 'Blunt Arrow Quiver Piece'),
  ('Vixen''s Entrapment', 'Embroidered Gloves'),
  ('Yriel''s Fostering', 'Exquisite Leather'),
  ('Wall of Brambles', 'Plate Vest'),
  ('Allelopathy', 'Sorcerer Gloves'),
  ('Atziri''s Step', 'Slink Boots'),
  ('Aurseize', 'Steelscale Gauntlets'),
  ('Craiceann''s Chitin', 'Magistrate Crown'),
  ('Craiceann''s Pincers', 'Titan Gauntlets'),
  ('Craiceann''s Tracks', 'Goliath Greaves'),
  ('Daresso''s Defiance', 'Full Dragonscale'),
  ('Doryani''s Delusion', 'Slink Boots'),
  ('Drillneck', 'Penetrating Arrow Quiver'),
  ('First Piece of Directions', 'Blunt Arrow Quiver Piece'),
  ('Kaom''s Roots', 'Titan Greaves'),
  ('Memory Vault', 'Praetor Crown'),
  ('Obscurantis', 'Lion Pelt'),
  ('Prism Guardian', 'Archon Kite Shield'),
  ('Rathpith Globe', 'Titanium Spirit Shield'),
  ('Saqawal''s Nest', 'Blood Raiment'),
  ('Shadows and Dust', 'Clasped Mitts'),
  ('Soul Strike', 'Spike-Point Arrow Quiver'),
  ('Starkonja''s Head', 'Silken Hood'),
  ('Steppan Eard', 'Sorcerer Boots'),
  ('Unyielding Flame', 'Archon Kite Shield'),
  ('Voidwalker', 'Murder Boots'),
  ('Wildwrap', 'Strapped Leather'),
  ('Saqawal''s Flock', 'Silken Hood'),
  ('Apep''s Slumber', 'Ancient Spirit Shield'),
  ('Abyssus', 'Ezomyte Burgonet'),
  ('Alpha''s Howl', 'Sinner Tricorne'),
  ('Architect''s Hand', 'Strapped Mitts'),
  ('Brinerot Flag', 'Tarnished Spirit Shield'),
  ('Brinerot Whalers', 'Trapper Boots'),
  ('Broken Faith', 'Archon Kite Shield'),
  ('Cherrubim''s Maleficence', 'Triumphant Lamellar'),
  ('Cospri''s Will', 'Assassin''s Garb'),
  ('Cragfall', 'Serrated Arrow Quiver'),
  ('Crystal Vault', 'Latticed Ringmail'),
  ('Dance of the Offered', 'Shackled Boots'),
  ('Demon Stitcher', 'Satin Gloves'),
  ('Doedre''s Skin', 'Widowsilk Robe'),
  ('Doryani''s Fist', 'Vaal Gauntlets'),
  ('Duskblight', 'Ironscale Boots'),
  ('Ezomyte Hold', 'Iron Hat'),
  ('Flamesight', 'Solaris Circlet'),
  ('Flesh and Spirit', 'Ironscale Gauntlets'),
  ('Galesight', 'Solaris Circlet'),
  ('Geofri''s Sanctuary', 'Elegant Ringmail'),
  ('Haemophilia', 'Serpentscale Gauntlets'),
  ('Heretic''s Veil', 'Deicide Mask'),
  ('Incandescent Heart', 'Saintly Chainmail'),
  ('Kaltensoul', 'Painted Buckler'),
  ('Leper''s Alms', 'Mirrored Spiked Shield'),
  ('Lochtonial Caress', 'Iron Gauntlets'),
  ('Maligaro''s Virtuosity', 'Deerskin Gloves'),
  ('Mask of the Spirit Drinker', 'Crusader Helmet'),
  ('Mind of the Council', 'Harlequin Mask'),
  ('Rat''s Nest', 'Ursine Pelt'),
  ('Saffell''s Frame', 'Branded Kite Shield'),
  ('Saqawal''s Talons', 'Hydrascale Boots'),
  ('Saqawal''s Winds', 'Soldier Gloves'),
  ('Scold''s Bridle', 'Mind Cage'),
  ('Sentari''s Answer', 'Brass Spirit Shield'),
  ('Skirmish', 'Two-Point Arrow Quiver'),
  ('The Baron', 'Close Helmet'),
  ('The Beast Fur Shawl', 'Vaal Regalia'),
  ('The Coming Calamity', 'Destroyer Regalia'),
  ('The Formless Flame', 'Siege Helmet'),
  ('The Infinite Pursuit', 'Goliath Greaves'),
  ('Thirst for Horrors', 'War Buckler'),
  ('Thunderfist', 'Murder Mitts'),
  ('Thundersight', 'Solaris Circlet'),
  ('Tinkerskin', 'Sadist Garb'),
  ('Victario''s Charity', 'Laminated Kite Shield'),
  ('Victario''s Influence', 'Lacquered Garb'),
  ('Vis Mortis', 'Necromancer Silks'),
  ('Voidbringer', 'Conjurer Gloves'),
  ('Wanderlust', 'Wool Shoes'),
  ('Windscream', 'Reinforced Greaves'),
  ('Zeel''s Amplifier', 'Polished Spiked Shield'),
  ('The Rat Cage', 'Sharkskin Tunic'),
  ('Greed''s Embrace', 'Golden Plate'),
  ('Doedre''s Scorn', 'Lunaris Circlet'),
  ('Ahn''s Heritage', 'Colossal Tower Shield'),
  ('Atziri''s Mirror', 'Golden Buckler'),
  ('Blasphemer''s Grasp', 'Assassin''s Mitts'),
  ('Bloodbond', 'Bone Armour'),
  ('Chernobog''s Pillar', 'Ebony Tower Shield'),
  ('Crown of the Pale King', 'Regicide Mask'),
  ('Doedre''s Tenure', 'Velvet Gloves'),
  ('Empire''s Grasp', 'Goliath Gauntlets'),
  ('Facebreaker', 'Strapped Mitts'),
  ('Gorgon''s Gaze', 'Regicide Mask'),
  ('Great Old One''s Ward', 'Corrugated Buckler'),
  ('Leer Cast', 'Festival Mask'),
  ('Lightning Coil', 'Desert Brigandine'),
  ('Malachai''s Mark', 'Murder Mitts'),
  ('Maloney''s Nightfall', 'Blunt Arrow Quiver'),
  ('March of the Legion', 'Legion Boots'),
  ('Matua Tupuna', 'Tarnished Spirit Shield'),
  ('Meginord''s Vise', 'Steel Gauntlets'),
  ('Mutewind Whispersteps', 'Serpentscale Boots'),
  ('Oskarm', 'Nubuck Gloves'),
  ('Ralakesh''s Impatience', 'Riveted Boots'),
  ('Redblade Tramplers', 'Ancient Greaves'),
  ('Repentance', 'Crusader Gloves'),
  ('Rime Gaze', 'Mind Cage'),
  ('Rise of the Phoenix', 'Mosaic Kite Shield'),
  ('Sadima''s Touch', 'Wool Gloves'),
  ('Soul Mantle', 'Spidersilk Robe'),
  ('Southbound', 'Soldier Gloves'),
  ('Sundance', 'Clasped Boots'),
  ('The Blood Dance', 'Sharkskin Boots'),
  ('The Bringer of Rain', 'Nightmare Bascinet'),
  ('The Broken Crown', 'Prophet Crown'),
  ('The Peregrine', 'Visored Sallet'),
  ('The Restless Ward', 'Carnal Armour'),
  ('Titucius'' Span', 'Reinforced Tower Shield'),
  ('Trolltimber Spire', 'Cedar Tower Shield'),
  ('Vaal Caress', 'Bronzescale Gauntlets'),
  ('Voll''s Vision', 'Praetor Crown'),
  ('Worldcarver', 'Dragonscale Gauntlets'),
  ('Saemus'' Gift', 'Spike-Point Arrow Quiver'),
  ('The Covenant', 'Spidersilk Robe'),
  ('Viper''s Scales', 'Full Scale Armour'),
  ('Glitterdisc', 'Burnished Spiked Shield'),
  ('The Eternal Apple', 'Chiming Spirit Shield'),
  ('Alberon''s Warpath', 'Soldier Boots'),
  ('Kongming''s Stratagem', 'Ivory Spirit Shield'),
  ('Maligaro''s Lens', 'Compound Spiked Shield'),
  ('Skullhead', 'Secutor Helm'),
  ('Wraithlord', 'Bone Circlet'),
  ('Chitus'' Apex', 'Necromancer Circlet'),
  ('Giantsbane', 'Bronze Gauntlets'),
  ('Ahn''s Contempt', 'Praetor Crown'),
  ('Ambu''s Charge', 'Crusader Chainmail'),
  ('Asenath''s Gentle Touch', 'Silk Gloves'),
  ('Asenath''s Mark', 'Iron Circlet'),
  ('Black Sun Crest', 'Lacquered Helmet'),
  ('Briskwrap', 'Strapped Leather'),
  ('Bronn''s Lithe', 'Cutthroat''s Garb'),
  ('Chains of Command', 'Saintly Chainmail'),
  ('Cloak of Flame', 'Scholar''s Robe'),
  ('Crest of Perandus', 'Pine Buckler'),
  ('Crown of Eyes', 'Hubris Circlet'),
  ('Curtain Call', 'Plague Mask'),
  ('Daresso''s Courage', 'Baroque Round Shield'),
  ('Darkray Vectors', 'Dragonscale Boots'),
  ('Deerstalker', 'Deerskin Boots'),
  ('Dendrobate', 'Sentinel Jacket'),
  ('Gang''s Momentum', 'Legion Boots'),
  ('Geofri''s Crest', 'Great Crown'),
  ('Heatshiver', 'Leather Hood'),
  ('Hrimnor''s Resolve', 'Samite Helmet'),
  ('Hrimsorrow', 'Goathide Gloves'),
  ('Hyrri''s Bite', 'Sharktooth Arrow Quiver'),
  ('Icetomb', 'Latticed Ringmail'),
  ('Infernal Mantle', 'Widowsilk Robe'),
  ('Iron Heart', 'Crusader Plate'),
  ('Jaws of Agony', 'Supreme Spiked Shield'),
  ('Kalisa''s Grace', 'Samite Gloves'),
  ('Kingsguard', 'Conquest Chainmail'),
  ('Kitava''s Thirst', 'Zealot Helmet'),
  ('Lioneye''s Paws', 'Bronzescale Boots'),
  ('Lioneye''s Vision', 'Crusader Plate'),
  ('Malachai''s Loop', 'Harmonic Spirit Shield'),
  ('Malachai''s Simula', 'Iron Mask'),
  ('Mindspiral', 'Aventail Helmet'),
  ('Mutewind Pennant', 'Enameled Buckler'),
  ('Ondar''s Clasp', 'Wrapped Mitts'),
  ('Rearguard', 'Broadhead Arrow Quiver'),
  ('Redblade Banner', 'Painted Tower Shield'),
  ('Solaris Lorica', 'Copper Plate'),
  ('Stormcharger', 'Plated Greaves'),
  ('Surgebinders', 'Dragonscale Gauntlets'),
  ('The Embalmer', 'Carnal Mitts'),
  ('Three-step Assault', 'Shagreen Boots'),
  ('Victario''s Flight', 'Goathide Boots'),
  ('Voll''s Protector', 'Holy Chainmail'),
  ('Wyrmsign', 'Wyrmscale Gauntlets'),
  ('Zahndethus'' Cassock', 'Sage''s Robe'),
  ('Asphyxia''s Wrath', 'Two-Point Arrow Quiver'),
  ('Bramblejack', 'Plate Vest'),
  ('Crown of Thorns', 'Vine Circlet'),
  ('Deidbell', 'Gilded Sallet'),
  ('Foxshade', 'Wild Leather'),
  ('Mark of the Red Covenant', 'Tribal Circlet'),
  ('Nomic''s Storm', 'Strapped Boots'),
  ('Shackles of the Wretched', 'Chain Gloves'),
  ('Shavronne''s Pace', 'Scholar Boots'),
  ('Snakebite', 'Assassin''s Mitts'),
  ('Speaker''s Wreath', 'Prophet Crown'),
  ('Springleaf', 'Plank Kite Shield'),
  ('The Three Dragons', 'Golden Mask'),
  ('Thousand Teeth Temu', 'Vaal Buckler'),
  ('Wake of Destruction', 'Mesh Boots'),
  ('Bones of Ullr', 'Silk Slippers'),
  ('Dialla''s Malefaction', 'Sage''s Robe'),
  ('Veruso''s Battering Rams', 'Titan Gauntlets'),
  ('Veil of the Night', 'Great Helmet'),
  ('Slitherpinch', 'Bronzescale Gauntlets'),
  ('Ashrend', 'Buckskin Tunic'),
  ('Dusktoe', 'Ironscale Boots'),
  ('Chalice of Horrors', 'War Buckler'),
  ('Wondertrap', 'Velvet Slippers'),
  ('Blackgleam', 'Fire Arrow Quiver'),
  ('Craghead', 'Serrated Arrow Quiver'),
  ('Thousand Ribbons', 'Simple Robe'),
  ('Wheel of the Stormsail', 'Rotted Round Shield'),
  ('Ezomyte Peak', 'Iron Hat'),
  ('Fairgraves'' Tricorne', 'Tricorne'),
  ('Kaltenhalt', 'Painted Buckler'),
  ('Lightbane Raiment', 'Ornate Ringmail'),
  ('The Deep One''s Hide', 'Studded Round Shield'),
  ('Honourhome', 'Soldier Helmet');