INSERT INTO uniques (name, base)
  VALUES
  ('Duskdawn', 'Maelström Staff'),
  ('Void Battery', 'Prophecy Wand'),
  ('Shade of Solaris', 'Sage Wand'),
  ('United in Dream', 'Cutlass'),
  ('Arborix', 'Assassin Bow'),
  ('Windripper', 'Imperial Bow'),
  ('Starforge', 'Infernal Sword'),
  ('Grelwood Shank', 'Eternal Sword'),
  ('Martyr of Innocence', 'Highborn Staff'),
  ('Arakaali''s Fang', 'Fiend Dagger'),
  ('Uul-Netol''s Embrace', 'Vaal Axe'),
  ('The Grey Spire', 'Judgement Staff'),
  ('Voidforge', 'Infernal Sword'),
  ('Cospri''s Malice', 'Jewelled Foil'),
  ('Disintegrator', 'Maelström Staff'),
  ('Hand of Wisdom and Action', 'Imperial Claw'),
  ('Doryani''s Catalyst', 'Vaal Sceptre'),
  ('Rigwald''s Savagery', 'Royal Axe'),
  ('Breath of the Council', 'Carnal Sceptre'),
  ('Paradoxica', 'Vaal Rapier'),
  ('Atziri''s Disfavour', 'Vaal Axe'),
  ('Rigwald''s Command', 'Midnight Blade'),
  ('Razor of the Seventh Sun', 'Midnight Blade'),
  ('Tulfall', 'Tornado Wand'),
  ('Fate of the Vaal', 'Gemstone Sword'),
  ('Cerberus Limb', 'Blood Sceptre'),
  ('Soulwrest', 'Ezomyte Staff'),
  ('The Poet''s Pen', 'Carved Wand'),
  ('Kingmaker', 'Despot Axe'),
  ('The Rippling Thoughts', 'Legion Sword'),
  ('The Crimson Storm', 'Steelwood Bow'),
  ('The Dancing Duo', 'Reaver Sword'),
  ('The Goddess Scorned', 'Elegant Sword'),
  ('Varunastra', 'Vaal Blade'),
  ('Dreadbeak', 'Rusted Sword'),
  ('Death''s Opus', 'Death Bow'),
  ('Dreadsurge', 'Cleaver'),
  ('The Scourge', 'Terror Claw'),
  ('The Tempest', 'Long Bow'),
  ('Beltimber Blade', 'Eternal Sword'),
  ('Realm Ender', 'Iron Staff'),
  ('Spine of the First Claimant', 'Iron Sceptre'),
  ('Nebuloch', 'Nightmare Mace'),
  ('Cameria''s Avarice', 'Gavel'),
  ('Soul Taker', 'Siege Axe'),
  ('The Gryphon', 'Jade Hatchet'),
  ('Silverbough', 'Crude Bow'),
  ('Corona Solaris', 'Crystal Wand'),
  ('Doomfletch''s Prism', 'Royal Bow'),
  ('Queen''s Escape', 'Ornate Sword'),
  ('Sanguine Gambol', 'Skinning Knife'),
  ('Severed in Sleep', 'Cutlass'),
  ('The Cauteriser', 'Woodsplitter'),
  ('The Enmity Divine', 'Imperial Staff'),
  ('The Stormwall', 'Royal Staff'),
  ('Xirgil''s Crank', 'Coiled Staff'),
  ('Xoph''s Nurture', 'Citadel Bow'),
  ('Mjölner', 'Gavel'),
  ('Shimmeron', 'Tornado Wand'),
  ('Tidebreaker', 'Imperial Maul'),
  ('Agnerod East', 'Imperial Staff'),
  ('Agnerod North', 'Imperial Staff'),
  ('Agnerod South', 'Imperial Staff'),
  ('Agnerod West', 'Imperial Staff'),
  ('Amplification Rod', 'Spiraled Wand'),
  ('Bloodseeker', 'Hellion''s Paw'),
  ('Brutus'' Lead Sprinkler', 'Ritual Sceptre'),
  ('Chaber Cairn', 'Great Mallet'),
  ('Geofri''s Devotion', 'Brass Maul'),
  ('Kitava''s Feast', 'Void Axe'),
  ('Mirebough', 'Gnarled Branch'),
  ('Slivertongue', 'Harbinger Bow'),
  ('The Harvest', 'Jasper Chopper'),
  ('Trypanon', 'Great Mallet'),
  ('Brightbeak', 'War Hammer'),
  ('Ahn''s Might', 'Midnight Blade'),
  ('Apep''s Rage', 'Opal Wand'),
  ('Augyre', 'Void Sceptre'),
  ('Axiom Perpetuum', 'Bronze Sceptre'),
  ('Balefire', 'Opal Sceptre'),
  ('Brain Rattler', 'Meatgrinder'),
  ('Chin Sol', 'Assassin Bow'),
  ('Divinarius', 'Imperial Skean'),
  ('Doon Cuebiyari', 'Vaal Sceptre'),
  ('Edge of Madness', 'Etched Greatsword'),
  ('Hand of Thought and Motion', 'Blinder'),
  ('Heartbreaker', 'Royal Skean'),
  ('Hegemony''s Era', 'Judgement Staff'),
  ('Hopeshredder', 'Ranger Bow'),
  ('Hrimnor''s Dirge', 'Sledgehammer'),
  ('Ichimonji', 'Corsair Sword'),
  ('Innsbury Edge', 'Elder Sword'),
  ('Izaro''s Dilemma', 'Imperial Claw'),
  ('Lifesprig', 'Driftwood Wand'),
  ('Lioneye''s Glare', 'Imperial Bow'),
  ('Ngamahu''s Flame', 'Abyssal Axe'),
  ('Panquetzaliztli', 'Jagged Maul'),
  ('Piscator''s Vigil', 'Tornado Wand'),
  ('Pledge of Hands', 'Judgement Staff'),
  ('Quill Rain', 'Short Bow'),
  ('Reach of the Council', 'Spine Bow'),
  ('Singularity', 'Platinum Sceptre'),
  ('Story of the Vaal', 'Variscite Blade'),
  ('The Dark Seer', 'Shadow Sceptre'),
  ('The Searing Touch', 'Lathi'),
  ('The Tempestuous Steel', 'War Sword'),
  ('Touch of Anguish', 'Imperial Claw'),
  ('Tulborn', 'Spiraled Wand'),
  ('Uul-Netol''s Kiss', 'Labrys'),
  ('Vulconus', 'Demon Dagger'),
  ('Xoph''s Inception', 'Bone Bow'),
  ('Jorrhast''s Blacksteel', 'Steelhead'),
  ('Allure', 'Vaal Claw'),
  ('Ashcaller', 'Quartz Wand'),
  ('Bino''s Kitchen Knife', 'Slaughter Knife'),
  ('Cane of Unravelling', 'Ezomyte Staff'),
  ('Chitus'' Needle', 'Elegant Foil'),
  ('Clayshaper', 'Rock Breaker'),
  ('Death''s Hand', 'Karui Sceptre'),
  ('Doomsower', 'Lion Sword'),
  ('Dreamfeather', 'Eternal Sword'),
  ('Dying Breath', 'Iron Staff'),
  ('Earendel''s Embrace', 'Grinning Fetish'),
  ('Hyaon''s Fury', 'Legion Sword'),
  ('Kaom''s Primacy', 'Karui Chopper'),
  ('Last Resort', 'Nailed Fist'),
  ('Midnight Bargain', 'Engraved Wand'),
  ('Mon''tregul''s Grasp', 'Void Sceptre'),
  ('Mortem Morsu', 'Fright Claw'),
  ('Ornament of the East', 'Gut Ripper'),
  ('Oro''s Sacrifice', 'Infernal Sword'),
  ('Rive', 'Terror Claw'),
  ('Sire of Shards', 'Serpentine Staff'),
  ('Taryn''s Shiver', 'Maelström Staff'),
  ('The Goddess Bound', 'Whalebone Rapier'),
  ('The Screaming Eagle', 'Jade Hatchet'),
  ('The Supreme Truth', 'Crystal Sceptre'),
  ('The Wasp Nest', 'Throat Stabber'),
  ('Voltaxic Rift', 'Spine Bow'),
  ('Jack, the Axe', 'Vaal Hatchet'),
  ('Terminus Est', 'Tiger Sword'),
  ('Hiltless', 'Reaver Sword'),
  ('Queen''s Decree', 'Ornate Sword'),
  ('Lakishu''s Blade', 'Elegant Sword'),
  ('Mark of the Doubting Knight', 'Platinum Kris'),
  ('Prismatic Eclipse', 'Twilight Blade'),
  ('The Princess', 'Sabre'),
  ('Lavianga''s Wisdom', 'War Hammer'),
  ('Advancing Fortress', 'Gut Ripper'),
  ('Callinellus Malleus', 'Auric Mace'),
  ('Chober Chaber', 'Great Mallet'),
  ('Daresso''s Passion', 'Estoc'),
  ('Death''s Harp', 'Death Bow'),
  ('Debeon''s Dirge', 'Despot Axe'),
  ('Doomfletch', 'Royal Bow'),
  ('Dyadus', 'Infernal Axe'),
  ('Ephemeral Edge', 'Dusk Blade'),
  ('Essentia Sanguis', 'Vaal Claw'),
  ('Ewar''s Mirage', 'Antique Rapier'),
  ('Femurs of the Saints', 'Primordial Staff'),
  ('Fidelitas'' Spike', 'Jagged Foil'),
  ('Flesh-Eater', 'Dream Mace'),
  ('Hezmana''s Bloodlust', 'Vaal Axe'),
  ('Kondo''s Pride', 'Ezomyte Blade'),
  ('Kongor''s Undying Rage', 'Terror Maul'),
  ('Moonbender''s Wing', 'Tomahawk'),
  ('Null''s Inclination', 'Ranger Bow'),
  ('Nuro''s Harp', 'Harbinger Bow'),
  ('Nycta''s Lantern', 'Crystal Sceptre'),
  ('Obliteration', 'Demon''s Horn'),
  ('Quecholli', 'Jagged Maul'),
  ('Reaper''s Pursuit', 'Shadow Axe'),
  ('Rebuke of the Vaal', 'Vaal Blade'),
  ('Redbeak', 'Rusted Sword'),
  ('Reverberation Rod', 'Spiraled Wand'),
  ('Rigwald''s Charge', 'Highland Blade'),
  ('Scaeva', 'Gladius'),
  ('Silverbranch', 'Crude Bow'),
  ('Sinvicta''s Mettle', 'Ezomyte Axe'),
  ('Storm Cloud', 'Long Bow'),
  ('Storm Prison', 'Carved Wand'),
  ('Taproot', 'Ambusher'),
  ('The Blood Reaper', 'Headsman Axe'),
  ('The Consuming Dark', 'Fiend Dagger'),
  ('The Dancing Dervish', 'Reaver Sword'),
  ('The Whispering Ice', 'Vile Staff'),
  ('White Wind', 'Imperial Skean'),
  ('Widowmaker', 'Boot Blade'),
  ('Wings of Entropy', 'Sundering Axe'),
  ('Al Dhih', 'Timeworn Claw'),
  ('Aurumvorax', 'Basket Rapier'),
  ('Bloodplay', 'Stiletto'),
  ('Cybil''s Paw', 'Thresher Claw'),
  ('Dreadarc', 'Cleaver'),
  ('Eclipse Solaris', 'Crystal Wand'),
  ('Frostbreath', 'Ornate Mace'),
  ('Infractem', 'Decimation Bow'),
  ('Limbsplit', 'Woodsplitter'),
  ('Marohi Erqi', 'Karui Maul'),
  ('Mightflay', 'Flaying Knife'),
  ('Moonsorrow', 'Imbued Wand'),
  ('Wideswing', 'Poleaxe'),
  ('Wildslash', 'Awl'),
  ('Pillar of the Caged God', 'Long Staff'),
  ('Relentless Fury', 'Decorative Axe'),
  ('Tremor Rod', 'Military Staff'),
  ('Darkscorn', 'Assassin Bow'),
  ('Bitterdream', 'Shadow Sceptre'),
  ('Realmshaper', 'Iron Staff'),
  ('Geofri''s Baptism', 'Brass Maul'),
  ('Gorebreaker', 'Spiked Club'),
  ('The Blood Thorn', 'Gnarled Branch'),
  ('Ungil''s Gauche', 'Boot Knife'),
  ('Cameria''s Maul', 'Gavel'),
  ('Goredrill', 'Skinning Knife'),
  ('Hrimnor''s Hymn', 'Sledgehammer'),
  ('Iron Commander', 'Death Bow'),
  ('The Stormheart', 'Royal Staff'),
  ('Fencoil', 'Gnarled Branch'),
  ('Twyzel', 'Sage Wand'),
  ('Voidhome', 'Dread Maul'),
  ('Abberath''s Horn', 'Goat''s Horn'),
  ('Roth''s Reach', 'Recurve Bow'),
  ('Shiversting', 'Bastard Sword');