INSERT INTO uniques (name, base)
  VALUES
  ('Headhunter', 'Leather Belt'),
  ('Zerphi''s Heart', 'Paua Amulet'),
  ('The Pandemonius', 'Jade Amulet'),
  ('The Halcyon', 'Jade Amulet'),
  ('Xoph''s Blood', 'Amber Amulet'),
  ('Xoph''s Heart', 'Amber Amulet'),
  ('Solstice Vigil', 'Onyx Amulet'),
  ('Presence of Chayula', 'Onyx Amulet'),
  ('Yoke of Suffering', 'Onyx Amulet'),
  ('Mark of the Shaper', 'Opal Ring'),
  ('Aul''s Uprising', 'Onyx Amulet'),
  ('The Taming', 'Prismatic Ring'),
  ('Choir of the Storm', 'Lapis Amulet'),
  ('Impresence', 'Onyx Amulet'),
  ('Berek''s Respite', 'Two-Stone Ring'),
  ('Voice of the Storm', 'Lapis Amulet'),
  ('Voll''s Devotion', 'Agate Amulet'),
  ('Eyes of the Greatwolf', 'Greatwolf Talisman'),
  ('The Pariah', 'Unset Ring'),
  ('Bisco''s Collar', 'Gold Amulet'),
  ('Bisco''s Leash', 'Heavy Belt'),
  ('Ventor''s Gamble', 'Gold Ring'),
  ('Blightwell', 'Clutching Talisman'),
  ('Star of Wraeclast', 'Ruby Amulet'),
  ('Natural Hierarchy', 'Rotfeather Talisman'),
  ('Coward''s Legacy', 'Chain Belt'),
  ('Precursor''s Emblem', 'Prismatic Ring'),
  ('Shavronne''s Revelation', 'Moonstone Ring'),
  ('Kaom''s Way', 'Coral Ring'),
  ('Rigwald''s Curse', 'Wereclaw Talisman'),
  ('Astramentis', 'Onyx Amulet'),
  ('The Flow Untethered', 'Cloth Belt'),
  ('Valako''s Sign', 'Topaz Ring'),
  ('Putembo''s Meadow', 'Topaz Ring'),
  ('The Primordial Chain', 'Coral Amulet'),
  ('Eye of Innocence', 'Citrine Amulet'),
  ('Precursor''s Emblem', 'Two-Stone Ring'),
  ('Gifts from Above', 'Diamond Ring'),
  ('The Ascetic', 'Gold Amulet'),
  ('Uzaza''s Mountain', 'Sapphire Ring'),
  ('Berek''s Grip', 'Two-Stone Ring'),
  ('Hinekora''s Sight', 'Onyx Amulet'),
  ('Thief''s Torment', 'Prismatic Ring'),
  ('Vivinsect', 'Unset Ring'),
  ('Ahkeli''s Valley', 'Ruby Ring'),
  ('The Tactician', 'Studded Belt'),
  ('Call of the Brotherhood', 'Two-Stone Ring'),
  ('Essence Worm', 'Unset Ring'),
  ('The Retch', 'Rustic Sash'),
  ('Ascent From Flesh', 'Chain Belt'),
  ('The Nomad', 'Studded Belt'),
  ('Timetwist', 'Moonstone Ring'),
  ('First Piece of Time', 'Cloth Belt Piece'),
  ('Karui Charge', 'Jade Amulet'),
  ('The Effigon', 'Gold Amulet'),
  ('Second Piece of Time', 'Cloth Belt Piece'),
  ('Hyperboreus', 'Leather Belt'),
  ('Le Heup of All', 'Iron Ring'),
  ('Mark of the Elder', 'Steel Ring'),
  ('Perandus Signet', 'Paua Ring'),
  ('Snakepit', 'Sapphire Ring'),
  ('Dream Fragments', 'Sapphire Ring'),
  ('Mark of Submission', 'Unset Ring'),
  ('Rigwald''s Crest', 'Two-Stone Ring'),
  ('Voidheart', 'Iron Ring'),
  ('Winterweave', 'Coral Ring'),
  ('Ahkeli''s Mountain', 'Ruby Ring'),
  ('Berek''s Pass', 'Two-Stone Ring'),
  ('Blood of Corruption', 'Amber Amulet'),
  ('Brinerot Mark', 'Unset Ring'),
  ('Doedre''s Damning', 'Paua Ring'),
  ('Faminebind', 'Rustic Sash'),
  ('Gloomfang', 'Blue Pearl Amulet'),
  ('Ngamahu Tiki', 'Coral Amulet'),
  ('Ngamahu''s Sign', 'Ruby Ring'),
  ('Night''s Hold', 'Black Maw Talisman'),
  ('Putembo''s Valley', 'Topaz Ring'),
  ('Pyre', 'Sapphire Ring'),
  ('Redblade Band', 'Unset Ring'),
  ('Stormfire', 'Opal Ring'),
  ('Tasalio''s Sign', 'Sapphire Ring'),
  ('Uzaza''s Meadow', 'Sapphire Ring'),
  ('Voideye', 'Unset Ring'),
  ('Auxium', 'Crystal Belt'),
  ('Death Rush', 'Amethyst Ring'),
  ('Emberwake', 'Ruby Ring'),
  ('Ming''s Heart', 'Amethyst Ring'),
  ('Mutewind Seal', 'Unset Ring'),
  ('Romira''s Banquet', 'Diamond Ring'),
  ('The Hungry Loop', 'Unset Ring'),
  ('Valyrium', 'Moonstone Ring'),
  ('Malachai''s Artifice', 'Unset Ring'),
  ('Heartbound Loop', 'Moonstone Ring'),
  ('Lori''s Lantern', 'Prismatic Ring'),
  ('The Warden''s Brand', 'Iron Ring'),
  ('Umbilicus Immortalis', 'Leather Belt'),
  ('Andvarius', 'Gold Ring'),
  ('Atziri''s Foible', 'Paua Amulet'),
  ('Bated Breath', 'Chain Belt'),
  ('Blackheart', 'Iron Ring'),
  ('Bloodboil', 'Coral Ring'),
  ('Bloodgrip', 'Marble Amulet'),
  ('Carnage Heart', 'Onyx Amulet'),
  ('Coward''s Chains', 'Chain Belt'),
  ('Cyclopean Coil', 'Leather Belt'),
  ('Daresso''s Salute', 'Citrine Amulet'),
  ('Darkness Enthroned', 'Stygian Vise'),
  ('Doryani''s Invitation', 'Heavy Belt'),
  ('Eye of Chayula', 'Onyx Amulet'),
  ('Feastbind', 'Rustic Sash'),
  ('Gluttony', 'Leather Belt'),
  ('Kaom''s Sign', 'Coral Ring'),
  ('Karui Ward', 'Jade Amulet'),
  ('Kikazaru', 'Topaz Ring'),
  ('Mokou''s Embrace', 'Ruby Ring'),
  ('Praxis', 'Paua Ring'),
  ('Ryslatha''s Coil', 'Studded Belt'),
  ('Sacrificial Heart', 'Paua Amulet'),
  ('Sibyl''s Lament', 'Coral Ring'),
  ('Timeclasp', 'Moonstone Ring'),
  ('Victario''s Acuity', 'Turquoise Amulet'),
  ('Belt of the Deceiver', 'Heavy Belt'),
  ('Dyadian Dawn', 'Heavy Belt'),
  ('Extractor Mentis', 'Agate Amulet'),
  ('Hyrri''s Truth', 'Jade Amulet'),
  ('Marylene''s Fallacy', 'Lapis Amulet'),
  ('Meginord''s Girdle', 'Heavy Belt'),
  ('Perandus Blazon', 'Cloth Belt'),
  ('Perquil''s Toe', 'Gold Amulet'),
  ('Perseverance', 'Vanguard Belt'),
  ('Soulthirst', 'Cloth Belt'),
  ('String of Servitude', 'Heavy Belt'),
  ('The Anvil', 'Amber Amulet'),
  ('Warped Timepiece', 'Turquoise Amulet'),
  ('The Magnate', 'Studded Belt'),
  ('The Aylardex', 'Agate Amulet'),
  ('Rashkaldor''s Patience', 'Jade Amulet'),
  ('Araku Tiki', 'Coral Amulet'),
  ('Immortal Flesh', 'Leather Belt'),
  ('Maligaro''s Cruelty', 'Turquoise Amulet'),
  ('Maligaro''s Restraint', 'Chain Belt'),
  ('Prismweave', 'Rustic Sash'),
  ('Shaper''s Seed', 'Agate Amulet'),
  ('Soul Tether', 'Cloth Belt'),
  ('Stone of Lazhwar', 'Lapis Amulet'),
  ('Sunblast', 'Cloth Belt'),
  ('Tear of Purity', 'Lapis Amulet'),
  ('Winterheart', 'Gold Amulet'),
  ('Wurm''s Molt', 'Leather Belt'),
  ('Sidhebreath', 'Paua Amulet'),
  ('Ungil''s Harmony', 'Turquoise Amulet'),
  ('The Ignomon', 'Gold Amulet'),
  ('Cragfall', 'Serrated Arrow Quiver'),
  ('Crystal Vault', 'Latticed Ringmail'),
  ('Dance of the Offered', 'Shackled Boots'),
  ('Demon Stitcher', 'Satin Gloves'),
  ('Doedre''s Skin', 'Widowsilk Robe'),
  ('Doryani''s Fist', 'Vaal Gauntlets'),
  ('Duskblight', 'Ironscale Boots'),
  ('Ezomyte Hold', 'Iron Hat'),
  ('Flamesight', 'Solaris Circlet'),
  ('Flesh and Spirit', 'Ironscale Gauntlets'),
  ('Galesight', 'Solaris Circlet'),
  ('Geofri''s Sanctuary', 'Elegant Ringmail'),
  ('Haemophilia', 'Serpentscale Gauntlets'),
  ('Heretic''s Veil', 'Deicide Mask'),
  ('Incandescent Heart', 'Saintly Chainmail'),
  ('Kaltensoul', 'Painted Buckler'),
  ('Leper''s Alms', 'Mirrored Spiked Shield'),
  ('Lochtonial Caress', 'Iron Gauntlets'),
  ('Maligaro''s Virtuosity', 'Deerskin Gloves'),
  ('Mask of the Spirit Drinker', 'Crusader Helmet'),
  ('Mind of the Council', 'Harlequin Mask'),
  ('Rat''s Nest', 'Ursine Pelt'),
  ('Saffell''s Frame', 'Branded Kite Shield'),
  ('Saqawal''s Talons', 'Hydrascale Boots'),
  ('Saqawal''s Winds', 'Soldier Gloves'),
  ('Scold''s Bridle', 'Mind Cage'),
  ('Sentari''s Answer', 'Brass Spirit Shield'),
  ('Skirmish', 'Two-Point Arrow Quiver'),
  ('The Baron', 'Close Helmet'),
  ('The Beast Fur Shawl', 'Vaal Regalia'),
  ('The Coming Calamity', 'Destroyer Regalia'),
  ('The Formless Flame', 'Siege Helmet'),
  ('The Infinite Pursuit', 'Goliath Greaves'),
  ('Thirst for Horrors', 'War Buckler'),
  ('Thunderfist', 'Murder Mitts'),
  ('Thundersight', 'Solaris Circlet'),
  ('Tinkerskin', 'Sadist Garb'),
  ('Tombfist', 'Steelscale Gauntlets'),
  ('Victario''s Charity', 'Laminated Kite Shield'),
  ('Victario''s Influence', 'Lacquered Garb'),
  ('Vis Mortis', 'Necromancer Silks'),
  ('Voidbringer', 'Conjurer Gloves'),
  ('Wanderlust', 'Wool Shoes'),
  ('Windscream', 'Reinforced Greaves'),
  ('Zeel''s Amplifier', 'Polished Spiked Shield'),
  ('The Rat Cage', 'Sharkskin Tunic'),
  ('Greed''s Embrace', 'Golden Plate'),
  ('Doedre''s Scorn', 'Lunaris Circlet'),
  ('Ahn''s Heritage', 'Colossal Tower Shield'),
  ('Atziri''s Mirror', 'Golden Buckler'),
  ('Blasphemer''s Grasp', 'Assassin''s Mitts'),
  ('Bloodbond', 'Bone Armour'),
  ('Chernobog''s Pillar', 'Ebony Tower Shield'),
  ('Crown of the Pale King', 'Regicide Mask'),
  ('Doedre''s Tenure', 'Velvet Gloves'),
  ('Empire''s Grasp', 'Goliath Gauntlets'),
  ('Facebreaker', 'Strapped Mitts'),
  ('Gorgon''s Gaze', 'Regicide Mask'),
  ('Great Old One''s Ward', 'Corrugated Buckler'),
  ('Leer Cast', 'Festival Mask'),
  ('Lightning Coil', 'Desert Brigandine'),
  ('Lightpoacher', 'Great Crown'),
  ('Malachai''s Mark', 'Murder Mitts'),
  ('Maloney''s Nightfall', 'Blunt Arrow Quiver'),
  ('March of the Legion', 'Legion Boots'),
  ('Matua Tupuna', 'Tarnished Spirit Shield'),
  ('Meginord''s Vise', 'Steel Gauntlets'),
  ('Mutewind Whispersteps', 'Serpentscale Boots'),
  ('Oskarm', 'Nubuck Gloves'),
  ('Ralakesh''s Impatience', 'Riveted Boots'),
  ('Redblade Tramplers', 'Ancient Greaves'),
  ('Repentance', 'Crusader Gloves'),
  ('Rime Gaze', 'Mind Cage'),
  ('Rise of the Phoenix', 'Mosaic Kite Shield'),
  ('Sadima''s Touch', 'Wool Gloves'),
  ('Soul Mantle', 'Spidersilk Robe'),
  ('Southbound', 'Soldier Gloves'),
  ('Sundance', 'Clasped Boots'),
  ('The Blood Dance', 'Sharkskin Boots'),
  ('The Bringer of Rain', 'Nightmare Bascinet'),
  ('The Broken Crown', 'Prophet Crown'),
  ('The Peregrine', 'Visored Sallet'),
  ('The Restless Ward', 'Carnal Armour'),
  ('Titucius'' Span', 'Reinforced Tower Shield'),
  ('Trolltimber Spire', 'Cedar Tower Shield'),
  ('Vaal Caress', 'Bronzescale Gauntlets'),
  ('Voll''s Vision', 'Praetor Crown'),
  ('Worldcarver', 'Dragonscale Gauntlets'),
  ('Saemus'' Gift', 'Spike-Point Arrow Quiver'),
  ('The Covenant', 'Spidersilk Robe'),
  ('Viper''s Scales', 'Full Scale Armour'),
  ('Glitterdisc', 'Burnished Spiked Shield'),
  ('The Eternal Apple', 'Chiming Spirit Shield'),
  ('Alberon''s Warpath', 'Soldier Boots'),
  ('Kongming''s Stratagem', 'Ivory Spirit Shield'),
  ('Maligaro''s Lens', 'Compound Spiked Shield'),
  ('Skullhead', 'Secutor Helm'),
  ('Wraithlord', 'Bone Circlet'),
  ('Chitus'' Apex', 'Necromancer Circlet'),
  ('Giantsbane', 'Bronze Gauntlets'),
  ('Ahn''s Contempt', 'Praetor Crown'),
  ('Ambu''s Charge', 'Crusader Chainmail'),
  ('Asenath''s Gentle Touch', 'Silk Gloves'),
  ('Asenath''s Mark', 'Iron Circlet'),
  ('Black Sun Crest', 'Lacquered Helmet'),
  ('Briskwrap', 'Strapped Leather'),
  ('Bronn''s Lithe', 'Cutthroat''s Garb'),
  ('Chains of Command', 'Saintly Chainmail'),
  ('Cloak of Flame', 'Scholar''s Robe'),
  ('Crest of Perandus', 'Pine Buckler'),
  ('Crown of Eyes', 'Hubris Circlet'),
  ('Curtain Call', 'Plague Mask'),
  ('Daresso''s Courage', 'Baroque Round Shield'),
  ('Darkray Vectors', 'Dragonscale Boots'),
  ('Deerstalker', 'Deerskin Boots'),
  ('Dendrobate', 'Sentinel Jacket'),
  ('Gang''s Momentum', 'Legion Boots'),
  ('Geofri''s Crest', 'Great Crown'),
  ('Heatshiver', 'Leather Hood'),
  ('Hrimnor''s Resolve', 'Samite Helmet'),
  ('Hrimsorrow', 'Goathide Gloves'),
  ('Hyrri''s Bite', 'Sharktooth Arrow Quiver'),
  ('Icetomb', 'Latticed Ringmail'),
  ('Infernal Mantle', 'Widowsilk Robe'),
  ('Iron Heart', 'Crusader Plate'),
  ('Jaws of Agony', 'Supreme Spiked Shield'),
  ('Kalisa''s Grace', 'Samite Gloves'),
  ('Kingsguard', 'Conquest Chainmail'),
  ('Kitava''s Thirst', 'Zealot Helmet'),
  ('Lioneye''s Paws', 'Bronzescale Boots'),
  ('Lioneye''s Vision', 'Crusader Plate'),
  ('Malachai''s Loop', 'Harmonic Spirit Shield'),
  ('Malachai''s Simula', 'Iron Mask'),
  ('Mindspiral', 'Aventail Helmet'),
  ('Mutewind Pennant', 'Enameled Buckler'),
  ('Ondar''s Clasp', 'Wrapped Mitts'),
  ('Rearguard', 'Broadhead Arrow Quiver'),
  ('Redblade Banner', 'Painted Tower Shield'),
  ('Solaris Lorica', 'Copper Plate'),
  ('Stormcharger', 'Plated Greaves'),
  ('Surgebinders', 'Dragonscale Gauntlets'),
  ('The Embalmer', 'Carnal Mitts'),
  ('Three-step Assault', 'Shagreen Boots'),
  ('Victario''s Flight', 'Goathide Boots'),
  ('Voll''s Protector', 'Holy Chainmail'),
  ('Wyrmsign', 'Wyrmscale Gauntlets'),
  ('Zahndethus'' Cassock', 'Sage''s Robe'),
  ('Asphyxia''s Wrath', 'Two-Point Arrow Quiver'),
  ('Bramblejack', 'Plate Vest'),
  ('Crown of Thorns', 'Vine Circlet'),
  ('Deidbell', 'Gilded Sallet'),
  ('Foxshade', 'Wild Leather'),
  ('Mark of the Red Covenant', 'Tribal Circlet'),
  ('Nomic''s Storm', 'Strapped Boots'),
  ('Shackles of the Wretched', 'Chain Gloves'),
  ('Shavronne''s Pace', 'Scholar Boots'),
  ('Snakebite', 'Assassin''s Mitts'),
  ('Speaker''s Wreath', 'Prophet Crown'),
  ('Springleaf', 'Plank Kite Shield'),
  ('The Three Dragons', 'Golden Mask'),
  ('Thousand Teeth Temu', 'Vaal Buckler'),
  ('Wake of Destruction', 'Mesh Boots'),
  ('Bones of Ullr', 'Silk Slippers'),
  ('Dialla''s Malefaction', 'Sage''s Robe'),
  ('Veruso''s Battering Rams', 'Titan Gauntlets'),
  ('Veil of the Night', 'Great Helmet'),
  ('Slitherpinch', 'Bronzescale Gauntlets'),
  ('Ashrend', 'Buckskin Tunic'),
  ('Dusktoe', 'Ironscale Boots'),
  ('Chalice of Horrors', 'War Buckler'),
  ('Wondertrap', 'Velvet Slippers'),
  ('Blackgleam', 'Fire Arrow Quiver'),
  ('Craghead', 'Serrated Arrow Quiver'),
  ('Thousand Ribbons', 'Simple Robe'),
  ('Wheel of the Stormsail', 'Rotted Round Shield'),
  ('Ezomyte Peak', 'Iron Hat'),
  ('Fairgraves'' Tricorne', 'Tricorne'),
  ('Kaltenhalt', 'Painted Buckler'),
  ('Lightbane Raiment', 'Ornate Ringmail'),
  ('The Deep One''s Hide', 'Studded Round Shield'),
  ('Honourhome', 'Soldier Helmet');