CREATE TABLE leagues (
  id           serial PRIMARY KEY,
  name         text UNIQUE NOT NULL,
  is_available boolean     NOT NULL DEFAULT TRUE,
  created_at   timestamp   NOT NULL DEFAULT now(),
  updated_at   timestamp   NOT NULL DEFAULT now()
);

INSERT INTO leagues (name, is_available)
VALUES
  ('Anarchy', FALSE),
  ('Onslaught', FALSE),
  ('Domination', TRUE),
  ('Nemesis', FALSE),
  ('Invasion', FALSE),
  ('Ambush', TRUE),
  ('Rampage', FALSE),
  ('Beyond', TRUE),
  ('Torment', TRUE),
  ('Bloodlines', TRUE),
  ('Warbands', TRUE),
  ('Tempest', TRUE),
  ('Talisman', FALSE),
  ('Perandus', TRUE),
  ('Prophecy', TRUE),
  ('Essence', TRUE),
  ('Breach', TRUE),
  ('Legacy', FALSE),
  ('Harbinger', TRUE),
  ('Delirium', TRUE),
  ('Abyss', TRUE),
  ('Bestiary', FALSE),
  ('Incursion', FALSE),
  ('Delve', TRUE),
  ('Betrayal', TRUE),
  ('Synthesis', FALSE),
  ('Legion', TRUE),
  ('Blight', TRUE),
  ('Metamorph', TRUE);

DELETE FROM uniques WHERE id NOT IN (SELECT min(id) FROM uniques GROUP BY name, base);

ALTER TABLE uniques ADD CONSTRAINT name_base_unique UNIQUE (name, base);

INSERT INTO uniques (name, base)
VALUES
  ('Al Dhih', 'Timeworn Claw'),
  ('Asenath''s Gentle Touch', 'Silk Gloves'),
  ('Aukuna''s Will', 'Clasped Mitts'),
  ('Brutal Restraint', 'Timeless Jewel'),
  ('Darkscorn', 'Assassin Bow'),
  ('Divide and Conquer', 'Viridian Jewel'),
  ('Divinarius', 'Imperial Skean'),
  ('Elegant Hubris', 'Timeless Jewel'),
  ('Fractal Thoughts', 'Vaal Mask'),
  ('Glorious Vanity', 'Timeless Jewel'),
  ('Honourhome', 'Soldier Helmet'),
  ('Kaom''s Primacy', 'Karui Chopper'),
  ('Lavianga''s Wisdom', 'War Hammer'),
  ('Lethal Pride', 'Timeless Jewel'),
  ('Lioneye''s Paws', 'Bronzescale Boots'),
  ('Maligaro''s Virtuosity', 'Deerskin Gloves'),
  ('Marohi Erqi', 'Karui Maul'),
  ('Maw of Conquest', 'Steel Circlet'),
  ('Militant Faith', 'Timeless Jewel'),
  ('Pledge of Hands', 'Judgement Staff'),
  ('Rathpith Globe', 'Titanium Spirit Shield'),
  ('Rebuke of the Vaal', 'Vaal Blade'),
  ('Sign of the Sin Eater', 'Tyrant''s Sekhem'),
  ('Tavukai', 'Coral Amulet'),
  ('The Sorrow of the Divine', 'Sulphur Flask'),
  ('Voll''s Protector', 'Holy Chainmail'),
  ('Wreath of Phrecia', 'Iron Circlet'),
  ('Badge of the Brotherhood', 'Turquoise Amulet'),
  ('Breathstealer', 'Hydrascale Gauntlets'),
  ('Cold Iron Point', 'Ezomyte Dagger'),
  ('Cowl of the Ceraunophile', 'Solaris Circlet'),
  ('Cowl of the Cryophile', 'Silken Hood'),
  ('Cowl of the Thermophile', 'Ezomyte Burgonet'),
  ('Fortress Covenant', 'Cobalt Jewel'),
  ('Icefang Orbit', 'Iron Ring'),
  ('Machina Mitts', 'Murder Mitts'),
  ('Quickening Covenant', 'Viridian Jewel'),
  ('Rotting Legion', 'Loricated Ringmail'),
  ('Siegebreaker', 'Heavy Belt'),
  ('Sporeguard', 'Saint''s Hauberk'),
  ('The Jinxed Juju', 'Citrine Amulet'),
  ('The Stampede', 'Assassin''s Boots'),
  ('Torchoak Step', 'Antique Greaves'),
  ('Triad Grip', 'Mesh Gloves'),
  ('Venopuncture', 'Iron Ring'),
  ('Astral Projector', 'Topaz Ring'),
  ('Crown of the Inward Eye', 'Prophet Crown'),
  ('Eye of Malice', 'Callous Mask'),
  ('Fury Valve', 'Jade Amulet'),
  ('Hands of the High Templar', 'Crusader Gloves'),
  ('Leash of Oblation', 'Leather Belt'),
  ('Manastorm', 'Fossilised Spirit Shield'),
  ('Mistwall', 'Lacquered Buckler'),
  ('Mother''s Embrace', 'Heavy Belt'),
  ('Painseeker', 'Shagreen Gloves'),
  ('The Black Cane', 'Royal Sceptre'),
  ('The Ivory Tower', 'Saint''s Hauberk'),
  ('The Saviour', 'Legion Sword'),
  ('Thread of Hope', 'Crimson Jewel'),
  ('Warrior''s Legacy', 'Ruby Ring'),
  ('Willowgift', 'Jade Amulet'),
  ('Algor Mortis', 'Carnal Mitts'),
  ('Assailum', 'Sinner Tricorne'),
  ('Beacon of Madness', 'Two-Toned Boots'),
  ('Calamitous Visions', 'Small Cluster Jewel'),
  ('Kitava''s Teachings', 'Small Cluster Jewel'),
  ('Megalomaniac', 'Medium Cluster Jewel'),
  ('Natural Affinity', 'Small Cluster Jewel'),
  ('One With Nothing', 'Small Cluster Jewel'),
  ('Perfidy', 'Glorious Plate'),
  ('Profane Proxy', 'Unset Ring'),
  ('Split Personality', 'Prismatic Jewel'),
  ('The Front Line', 'Small Cluster Jewel'),
  ('The Interrogation', 'Small Cluster Jewel'),
  ('The Siege', 'Small Cluster Jewel'),
  ('Voices', 'Large Cluster Jewel')
ON CONFLICT DO NOTHING;

ALTER TABLE uniques
  ADD COLUMN league text NULL DEFAULT NULL,
  ADD CONSTRAINT fk_league FOREIGN KEY (league) REFERENCES leagues(name);

INSERT INTO uniques (name, base, league)
VALUES
  ('Ahkeli''s Meadow', 'Ruby Ring', 'Delve'),
  ('Ahkeli''s Mountain', 'Ruby Ring', 'Delve'),
  ('Ahkeli''s Valley', 'Ruby Ring', 'Delve'),
  ('Al Dhih', 'Timeworn Claw', 'Legion'),
  ('Algor Mortis', 'Carnal Mitts', 'Delirium'),
  ('Apep''s Slumber', 'Ancient Spirit Shield', 'Incursion'),
  ('Apep''s Supremacy', 'Vaal Spirit Shield', 'Incursion'),
  ('Architect''s Hand', 'Strapped Mitts', 'Incursion'),
  ('Ascent From Flesh', 'Chain Belt', 'Prophecy'),
  ('Asenath''s Gentle Touch', 'Silk Gloves', 'Legion'),
  ('Astral Projector', 'Topaz Ring', 'Metamorph'),
  ('Aukuna''s Will', 'Clasped Mitts', 'Legion'),
  ('Aul''s Uprising', 'Onyx Amulet', 'Delve'),
  ('Badge of the Brotherhood', 'Turquoise Amulet', 'Blight'),
  ('Beacon of Madness', 'Two-Toned Boots', 'Delirium'),
  ('Berek''s Grip', 'Two-Stone Ring', 'Betrayal'),
  ('Blightwell', 'Clutching Talisman', 'Talisman'),
  ('Blood of the Karui', 'Sanctified Life Flask', 'Synthesis'),
  ('Breath of the Council', 'Carnal Sceptre', 'Prophecy'),
  ('Breathstealer', 'Hydrascale Gauntlets', 'Blight'),
  ('Brinerot Flag', 'Tarnished Spirit Shield', 'Warbands'),
  ('Brinerot Mark', 'Unset Ring', 'Warbands'),
  ('Brinerot Whalers', 'Trapper Boots', 'Warbands'),
  ('Broken Faith', 'Archon Kite Shield', 'Warbands'),
  ('Brutal Restraint', 'Timeless Jewel', 'Legion'),
  ('Brutus'' Lead Sprinkler', 'Ritual Sceptre', 'Torment'),
  ('Bubonic Trail', 'Murder Boots', 'Abyss'),
  ('Calamitous Visions', 'Small Cluster Jewel', 'Delirium'),
  ('Cerberus Limb', 'Blood Sceptre', 'Delve'),
  ('Choir of the Storm', 'Lapis Amulet', 'Breach'),
  ('Cinderswallow Urn', 'Silver Flask', 'Betrayal'),
  ('Circle of Anguish', 'Ruby Ring', 'Synthesis'),
  ('Circle of Fear', 'Sapphire Ring', 'Synthesis'),
  ('Circle of Guilt', 'Iron Ring', 'Synthesis'),
  ('Circle of Nostalgia', 'Amethyst Ring', 'Synthesis'),
  ('Circle of Regret', 'Topaz Ring', 'Synthesis'),
  ('Command of the Pit', 'Riveted Gloves', 'Delve'),
  ('Coward''s Chains', 'Chain Belt', 'Incursion'),
  ('Coward''s Legacy', 'Chain Belt', 'Incursion'),
  ('Cowl of the Ceraunophile', 'Solaris Circlet', 'Blight'),
  ('Cowl of the Cryophile', 'Silken Hood', 'Blight'),
  ('Cowl of the Thermophile', 'Ezomyte Burgonet', 'Blight'),
  ('Craiceann''s Carapace', 'Golden Plate', 'Bestiary'),
  ('Craiceann''s Chitin', 'Magistrate Crown', 'Bestiary'),
  ('Craiceann''s Pincers', 'Titan Gauntlets', 'Bestiary'),
  ('Craiceann''s Tracks', 'Goliath Greaves', 'Bestiary'),
  ('Crown of the Pale King', 'Regicide Mask', 'Tempest'),
  ('Crown of the Tyrant', 'Magistrate Crown', 'Delve'),
  ('Dance of the Offered', 'Shackled Boots', 'Incursion'),
  ('Daresso''s Salute', 'Citrine Amulet', 'Anarchy'),
  ('Darkness Enthroned', 'Stygian Vise', 'Abyss'),
  ('Darkscorn', 'Assassin Bow', 'Legion'),
  ('Death Rush', 'Amethyst Ring', 'Onslaught'),
  ('Divinarius', 'Imperial Skean', 'Legion'),
  ('Edge of Madness', 'Etched Greatsword', 'Beyond'),
  ('Elegant Hubris', 'Timeless Jewel', 'Legion'),
  ('Esh''s Mirror', 'Thorium Spirit Shield', 'Breach'),
  ('Esh''s Visage', 'Vaal Spirit Shield', 'Breach'),
  ('Eyes of the Greatwolf', 'Greatwolf Talisman', 'Talisman'),
  ('Faminebind', 'Rustic Sash', 'Talisman'),
  ('Farrul''s Bite', 'Harlequin Mask', 'Bestiary'),
  ('Farrul''s Chase', 'Slink Boots', 'Bestiary'),
  ('Farrul''s Fur', 'Triumphant Lamellar', 'Bestiary'),
  ('Farrul''s Pounce', 'Hydrascale Gauntlets', 'Bestiary'),
  ('Fate of the Vaal', 'Gemstone Sword', 'Incursion'),
  ('Feastbind', 'Rustic Sash', 'Talisman'),
  ('Fenumus'' Shroud', 'Widowsilk Robe', 'Bestiary'),
  ('Fenumus'' Spinnerets', 'Assassin''s Boots', 'Bestiary'),
  ('Fenumus'' Toxins', 'Necromancer Circlet', 'Bestiary'),
  ('Fenumus'' Weave', 'Carnal Mitts', 'Bestiary'),
  ('Flesh and Spirit', 'Ironscale Gauntlets', 'Rampage'),
  ('Fury Valve', 'Jade Amulet', 'Metamorph'),
  ('Garb of the Ephemeral', 'Savant''s Robe', 'Synthesis'),
  ('Gifts from Above', 'Diamond Ring', 'Anarchy'),
  ('Glorious Vanity', 'Timeless Jewel', 'Legion'),
  ('Grip of the Council', 'Arcanist Gloves', 'Prophecy'),
  ('Hale Negator', 'Mind Cage', 'Delve'),
  ('Hand of Thought and Motion', 'Blinder', 'Breach'),
  ('Hand of Wisdom and Action', 'Imperial Claw', 'Breach'),
  ('Headhunter', 'Leather Belt', 'Nemesis'),
  ('Hinekora''s Sight', 'Onyx Amulet', 'Prophecy'),
  ('Honourhome', 'Soldier Helmet', 'Legion'),
  ('Hyperboreus', 'Leather Belt', 'Betrayal'),
  ('Icefang Orbit', 'Iron Ring', 'Blight'),
  ('Jorrhast''s Blacksteel', 'Steelhead', 'Tempest'),
  ('Kaom''s Primacy', 'Karui Chopper', 'Legion'),
  ('Kintsugi', 'Exquisite Leather', 'Prophecy'),
  ('Kitava''s Teachings', 'Small Cluster Jewel', 'Delirium'),
  ('Lavianga''s Spirit', 'Sanctified Mana Flask', 'Legion'),
  ('Lethal Pride', 'Timeless Jewel', 'Legion'),
  ('Lightpoacher', 'Great Crown', 'Abyss'),
  ('Lioneye''s Paws', 'Bronzescale Boots', 'Legion'),
  ('Machina Mitts', 'Murder Mitts', 'Blight'),
  ('Maligaro''s Virtuosity', 'Deerskin Gloves', 'Legion'),
  ('Marohi Erqi', 'Karui Maul', 'Legion'),
  ('Mask of the Spirit Drinker', 'Crusader Helmet', 'Incursion'),
  ('Mask of the Stitched Demon', 'Magistrate Crown', 'Incursion'),
  ('Mask of the Tribunal', 'Magistrate Crown', 'Synthesis'),
  ('Maw of Conquest', 'Steel Circlet', 'Legion'),
  ('Megalomaniac', 'Medium Cluster Jewel', 'Delirium'),
  ('Militant Faith', 'Timeless Jewel', 'Legion'),
  ('Mind of the Council', 'Harlequin Mask', 'Prophecy'),
  ('Mother''s Embrace', 'Heavy Belt', 'Metamorph'),
  ('Mutewind Pennant', 'Enameled Buckler', 'Warbands'),
  ('Mutewind Seal', 'Unset Ring', 'Warbands'),
  ('Mutewind Whispersteps', 'Serpentscale Boots', 'Warbands'),
  ('Natural Affinity', 'Small Cluster Jewel', 'Delirium'),
  ('Natural Hierarchy', 'Rotfeather Talisman', 'Talisman'),
  ('Nebulis', 'Void Sceptre', 'Synthesis'),
  ('Ngamahu''s Sign', 'Ruby Ring', 'Bloodlines'),
  ('Night''s Hold', 'Black Maw Talisman', 'Talisman'),
  ('Null and Void', 'Legion Gloves', 'Rampage'),
  ('Offering to the Serpent', 'Legion Gloves', 'Synthesis'),
  ('Omeyocan', 'Carnal Boots', 'Incursion'),
  ('One With Nothing', 'Small Cluster Jewel', 'Delirium'),
  ('Paradoxica', 'Vaal Rapier', 'Betrayal'),
  ('Perepiteia', 'Ezomyte Spiked Shield', 'Synthesis'),
  ('Perfidy', 'Glorious Plate', 'Delirium'),
  ('Pledge of Hands', 'Judgement Staff', 'Legion'),
  ('Presence of Chayula', 'Onyx Amulet', 'Breach'),
  ('Putembo''s Meadow', 'Topaz Ring', 'Delve'),
  ('Putembo''s Mountain', 'Topaz Ring', 'Delve'),
  ('Putembo''s Valley', 'Topaz Ring', 'Delve'),
  ('Rathpith Globe', 'Titanium Spirit Shield', 'Legion'),
  ('Reach of the Council', 'Spine Bow', 'Prophecy'),
  ('Rebuke of the Vaal', 'Vaal Blade', 'Legion'),
  ('Redblade Band', 'Unset Ring', 'Warbands'),
  ('Redblade Banner', 'Painted Tower Shield', 'Warbands'),
  ('Redblade Tramplers', 'Ancient Greaves', 'Warbands'),
  ('Rigwald''s Command', 'Midnight Blade', 'Talisman'),
  ('Rigwald''s Crest', 'Two-Stone Ring', 'Talisman'),
  ('Rigwald''s Curse', 'Wereclaw Talisman', 'Talisman'),
  ('Rigwald''s Quills', 'Two-Point Arrow Quiver', 'Talisman'),
  ('Rigwald''s Savagery', 'Royal Axe', 'Talisman'),
  ('Rotting Legion', 'Loricated Ringmail', 'Blight'),
  ('Sacrificial Heart', 'Paua Amulet', 'Incursion'),
  ('Saqawal''s Flock', 'Silken Hood', 'Bestiary'),
  ('Saqawal''s Nest', 'Blood Raiment', 'Bestiary'),
  ('Saqawal''s Talons', 'Hydrascale Boots', 'Bestiary'),
  ('Saqawal''s Winds', 'Soldier Gloves', 'Bestiary'),
  ('Scold''s Bridle', 'Mind Cage', 'Torment'),
  ('Seven-League Step', 'Rawhide Boots', 'Perandus'),
  ('Severed in Sleep', 'Cutlass', 'Breach'),
  ('Shadows and Dust', 'Clasped Mitts', 'Rampage'),
  ('Shadowstitch', 'Sacrificial Garb', 'Incursion'),
  ('Shavronne''s Revelation', 'Moonstone Ring', 'Abyss'),
  ('Shroud of the Lightless', 'Carnal Armour', 'Abyss'),
  ('Sign of the Sin Eater', 'Tyrant''s Sekhem', 'Legion'),
  ('Skin of the Lords', 'Simple Robe', 'Breach'),
  ('Skin of the Loyal', 'Plate Vest', 'Breach'),
  ('Slavedriver''s Hand', 'Ambush Mitts', 'Incursion'),
  ('Soul Catcher', 'Quartz Flask', 'Incursion'),
  ('Soul Ripper', 'Quartz Flask', 'Incursion'),
  ('Sporeguard', 'Saint''s Hauberk', 'Blight'),
  ('Steppan Eard', 'Sorcerer Boots', 'Warbands'),
  ('Storm''s Gift', 'Assassin''s Mitts', 'Synthesis'),
  ('Story of the Vaal', 'Variscite Blade', 'Incursion'),
  ('String of Servitude', 'Heavy Belt', 'Incursion'),
  ('Tasalio''s Sign', 'Sapphire Ring', 'Bloodlines'),
  ('Tavukai', 'Coral Amulet', 'Legion'),
  ('Tempered Flesh', 'Crimson Jewel', 'Incursion'),
  ('Tempered Mind', 'Cobalt Jewel', 'Incursion'),
  ('Tempered Spirit', 'Viridian Jewel', 'Incursion'),
  ('The Anticipation', 'Ezomyte Tower Shield', 'Breach'),
  ('The Ascetic', 'Gold Amulet', 'Prophecy'),
  ('The Blue Dream', 'Cobalt Jewel', 'Breach'),
  ('The Blue Nightmare', 'Cobalt Jewel', 'Breach'),
  ('The Crimson Storm', 'Steelwood Bow', 'Betrayal'),
  ('The Dark Seer', 'Shadow Sceptre', 'Beyond'),
  ('The Devouring Diadem', 'Necromancer Circlet', 'Betrayal'),
  ('The Enmity Divine', 'Imperial Staff', 'Harbinger'),
  ('The Flow Untethered', 'Cloth Belt', 'Harbinger'),
  ('The Formless Flame', 'Siege Helmet', 'Breach'),
  ('The Formless Inferno', 'Royal Burgonet', 'Breach'),
  ('The Fracturing Spinner', 'Blunt Arrow Quiver', 'Harbinger'),
  ('The Front Line', 'Small Cluster Jewel', 'Delirium'),
  ('The Green Dream', 'Viridian Jewel', 'Breach'),
  ('The Green Nightmare', 'Viridian Jewel', 'Breach'),
  ('The Gull', 'Raven Mask', 'Domination'),
  ('The Halcyon', 'Jade Amulet', 'Breach'),
  ('The Harvest', 'Jasper Chopper', 'Beyond'),
  ('The Infinite Pursuit', 'Goliath Greaves', 'Breach'),
  ('The Interrogation', 'Small Cluster Jewel', 'Delirium'),
  ('The Pandemonius', 'Jade Amulet', 'Breach'),
  ('The Pariah', 'Unset Ring', 'Warbands'),
  ('The Perfect Form', 'Zodiac Leather', 'Breach'),
  ('The Queen''s Hunger', 'Vaal Regalia', 'Betrayal'),
  ('The Rat Cage', 'Sharkskin Tunic', 'Torment'),
  ('The Red Dream', 'Crimson Jewel', 'Breach'),
  ('The Red Nightmare', 'Crimson Jewel', 'Breach'),
  ('The Red Trail', 'Titan Greaves', 'Breach'),
  ('The Retch', 'Rustic Sash', 'Talisman'),
  ('The Rippling Thoughts', 'Legion Sword', 'Harbinger'),
  ('The Siege', 'Small Cluster Jewel', 'Delirium'),
  ('The Snowblind Grace', 'Coronal Leather', 'Breach'),
  ('The Sorrow of the Divine', 'Sulphur Flask', 'Legion'),
  ('The Stampede', 'Assassin''s Boots', 'Blight'),
  ('The Surrender', 'Ezomyte Tower Shield', 'Breach'),
  ('The Taming', 'Prismatic Ring', 'Harbinger'),
  ('The Unshattered Will', 'Archon Kite Shield', 'Harbinger'),
  ('Tombfist', 'Steelscale Gauntlets', 'Abyss'),
  ('Transcendent Flesh', 'Crimson Jewel', 'Incursion'),
  ('Transcendent Mind', 'Cobalt Jewel', 'Incursion'),
  ('Transcendent Spirit', 'Viridian Jewel', 'Incursion'),
  ('Trolltimber Spire', 'Cedar Tower Shield', 'Tempest'),
  ('Trypanon', 'Great Mallet', 'Perandus'),
  ('Tulborn', 'Spiraled Wand', 'Breach'),
  ('Tulfall', 'Tornado Wand', 'Breach'),
  ('Umbilicus Immortalis', 'Leather Belt', 'Perandus'),
  ('United in Dream', 'Cutlass', 'Breach'),
  ('Uul-Netol''s Embrace', 'Vaal Axe', 'Breach'),
  ('Uul-Netol''s Kiss', 'Labrys', 'Breach'),
  ('Uzaza''s Meadow', 'Sapphire Ring', 'Delve'),
  ('Uzaza''s Mountain', 'Sapphire Ring', 'Delve'),
  ('Uzaza''s Valley', 'Sapphire Ring', 'Delve'),
  ('Vaal Caress', 'Bronzescale Gauntlets', 'Bloodlines'),
  ('Varunastra', 'Vaal Blade', 'Perandus'),
  ('Venopuncture', 'Iron Ring', 'Blight'),
  ('Victario''s Acuity', 'Turquoise Amulet', 'Onslaught'),
  ('Vivinsect', 'Unset Ring', 'Betrayal'),
  ('Voice of the Storm', 'Lapis Amulet', 'Breach'),
  ('Voices', 'Large Cluster Jewel', 'Delirium'),
  ('Voideye', 'Unset Ring', 'Legion'),
  ('Warrior''s Legacy', 'Ruby Ring', 'Metamorph'),
  ('Wreath of Phrecia', 'Iron Circlet', 'Legion'),
  ('Xoph''s Blood', 'Amber Amulet', 'Breach'),
  ('Xoph''s Heart', 'Amber Amulet', 'Breach'),
  ('Xoph''s Inception', 'Bone Bow', 'Breach'),
  ('Xoph''s Nurture', 'Citadel Bow', 'Breach'),
  ('Ylfeban''s Trickery', 'Hubris Circlet', 'Tempest'),
  ('Zerphi''s Heart', 'Paua Amulet', 'Incursion'),
  ('Zerphi''s Last Breath', 'Grand Mana Flask', 'Perandus')
ON CONFLICT ON CONSTRAINT name_base_unique DO UPDATE SET league = EXCLUDED.league;