CREATE TABLE prophecies(
  id											serial					PRIMARY KEY,
  name									  text						UNIQUE NOT NULL,
  drop_enabled            boolean         NOT NULL          DEFAULT true,
  created_at							timestamp				NOT NULL 					DEFAULT now(),
  updated_at							timestamp				NOT NULL 					DEFAULT now()
);

INSERT INTO prophecies(name)
VALUES
  ('A Master Seeks Help'),
  ('A Valuable Combination'),
  ('Erasmus'' Gift'),
  ('Fated Connections'),
  ('Golden Touch'),
  ('Resistant to Change'),
  ('Smothering Tendrils'),
  ('The Beautiful Guide'),
  ('The Hardened Armour'),
  ('The Jeweller''s Touch'),
  ('The Sharpened Blade'),
  ('Touched by the Wind'),
  ('Trash to Treasure'),
  ('Vital Transformation'),
  ('A Dishonourable Death'),
  ('A Forest of False Idols'),
  ('A Rift in Time'),
  ('A Vision of Ice and Fire'),
  ('Agony at Dusk'),
  ('Ancient Doom'),
  ('Battle Hardened'),
  ('Black Devotion'),
  ('Blind Faith'),
  ('Blinding Light'),
  ('Burning Dread'),
  ('Cold Blooded Fury'),
  ('Cold Greed'),
  ('Crimson Hues'),
  ('Dance of Steel'),
  ('Dark Instincts'),
  ('Darktongue''s Shriek'),
  ('Dying Cry'),
  ('End of the Light'),
  ('Faith Exhumed'),
  ('Fire and Brimstone'),
  ('Fire and Ice'),
  ('From The Void'),
  ('Greed''s Folly'),
  ('Heavy Blows'),
  ('Last of the Wildmen'),
  ('Mouth of Horrors'),
  ('Nature''s Resilience'),
  ('Pleasure and Pain'),
  ('Power Magnified'),
  ('Severed Limbs'),
  ('Song of the Sekhema'),
  ('Sun''s Punishment'),
  ('The Apex Predator'),
  ('The Beginning and the End'),
  ('The Bishop''s Legacy'),
  ('The Bloody Flowers Redux'),
  ('The Bowstring''s Music'),
  ('The Dreaded Rhoa'),
  ('The Fall of an Empire'),
  ('The Flow of Energy'),
  ('The Great Leader of the North'),
  ('The Great Mind of the North'),
  ('The Karui Rebellion'),
  ('The King and the Brambles'),
  ('The King''s Path'),
  ('The Malevolent Witch'),
  ('The Mentor'),
  ('The Misunderstood Queen'),
  ('The Nightmare Awakens'),
  ('The Queen''s Sacrifice'),
  ('The Servant''s Heart'),
  ('The Silverwood'),
  ('The Snuffed Flame'),
  ('The Storm Spire'),
  ('Trapped in the Tower'),
  ('Winter''s Mournful Melodies'),
  ('Crushing Squall'),
  ('Fire from the Sky'),
  ('Ice from Above'),
  ('Lightning Falls'),
  ('The Undead Storm'),
  ('Vaal Winds'),
  ('A Call into the Void'),
  ('A Firm Foothold'),
  ('A Prodigious Hand'),
  ('A Whispered Prayer'),
  ('Abnormal Effulgence'),
  ('Against the Tide'),
  ('Baptism by Death'),
  ('Blood in the Eyes'),
  ('Blood of the Betrayed'),
  ('Cleanser of Sins'),
  ('Custodians of Silence'),
  ('Fear''s Wide Reach'),
  ('Fire, Wood and Stone'),
  ('Flesh of the Beast'),
  ('From Death Springs Life'),
  ('Graceful Flames'),
  ('Heart of the Fire'),
  ('Lost in the Pages'),
  ('Nemesis of Greed'),
  ('Notched Flesh'),
  ('Roth''s Legacy'),
  ('Storm on the Horizon'),
  ('Storm on the Reef'),
  ('Strong as a Bull'),
  ('The Brutal Enforcer'),
  ('The Eagle''s Cry'),
  ('The Flayed Man'),
  ('The Hollow Pledge'),
  ('The Lady in Black'),
  ('The Last Watch'),
  ('The Lost Undying'),
  ('The Mysterious Gift'),
  ('The Nest'),
  ('The Petrified'),
  ('The Prison Guard'),
  ('The Prison Key'),
  ('The Queen''s Vaults'),
  ('The Singular Spirit'),
  ('The Sinner''s Stone'),
  ('The Soulless Beast'),
  ('The Stockkeeper'),
  ('The Sword King''s Passion'),
  ('The Vanguard'),
  ('The Walking Mountain'),
  ('The Ward''s Ward'),
  ('The Watcher''s Watcher'),
  ('Weeping Death'),
  ('Wind and Thunder'),
  ('A Regal Death'),
  ('Erased from Memory'),
  ('Lasting Impressions'),
  ('Overflowing Riches'),
  ('The Alchemist'),
  ('The Corrupt'),
  ('The God of Misfortune'),
  ('Twice Enchanted'),
  ('An Unseen Peril'),
  ('Deadly Twins'),
  ('Defiled in the Sceptre'),
  ('Echoes of Witchcraft'),
  ('Ending the Torment'),
  ('Fallow At Last'),
  ('Forceful Exorcism'),
  ('Hidden Reinforcements'),
  ('Hidden Vaal Pathways'),
  ('Holding the Bridge'),
  ('In the Grasp of Corruption'),
  ('Living Fires'),
  ('Monstrous Treasure'),
  ('Mysterious Invaders'),
  ('Path of Betrayal'),
  ('Plague of Frogs'),
  ('Plague of Rats'),
  ('Pools of Wealth'),
  ('Possessed Foe'),
  ('Rebirth'),
  ('Risen Blood'),
  ('Soil, Worms and Blood'),
  ('The Brothers of Necromancy'),
  ('The Child of Lunaris'),
  ('The Cursed Choir'),
  ('The Dreamer''s Dream'),
  ('The Forgotten Garrison'),
  ('The Forgotten Soldiers'),
  ('The Four Feral Exiles'),
  ('The Hungering Swarm'),
  ('The Invader'),
  ('The Trembling Earth'),
  ('The Twins'),
  ('The Undead Brutes'),
  ('Undead Uprising'),
  ('Unnatural Energy'),
  ('Vaal Invasion'),
  ('Visions of the Drowned'),
  ('Waiting in Ambush'),
  ('Bountiful Traps'),
  ('Gilded Within'),
  ('Hunter''s Lesson'),
  ('Kalandra''s Craft'),
  ('Reforged Bonds'),
  ('The Dream Trial'),
  ('The Fortune Teller''s Collection'),
  ('The Lost Maps'),
  ('The Scout'),
  ('The Wealthy Exile'),
  ('Anarchy''s End I'),
  ('Anarchy''s End II'),
  ('Anarchy''s End III'),
  ('Anarchy''s End IV'),
  ('Beyond Sight I'),
  ('Beyond Sight II'),
  ('Beyond Sight III'),
  ('Beyond Sight IV'),
  ('Day of Sacrifice I'),
  ('Day of Sacrifice II'),
  ('Day of Sacrifice III'),
  ('Day of Sacrifice IV'),
  ('Deadly Rivalry I'),
  ('Deadly Rivalry II'),
  ('Deadly Rivalry III'),
  ('Deadly Rivalry IV'),
  ('Deadly Rivalry V'),
  ('Thaumaturgical History I'),
  ('Thaumaturgical History II'),
  ('Thaumaturgical History III'),
  ('Thaumaturgical History IV'),
  ('The Ambitious Bandit I'),
  ('The Ambitious Bandit II'),
  ('The Ambitious Bandit III'),
  ('The Feral Lord I'),
  ('The Feral Lord II'),
  ('The Feral Lord III'),
  ('The Feral Lord IV'),
  ('The Feral Lord V'),
  ('The Plaguemaw I'),
  ('The Plaguemaw II'),
  ('The Plaguemaw III'),
  ('The Plaguemaw IV'),
  ('The Plaguemaw V'),
  ('The Unbreathing Queen I'),
  ('The Unbreathing Queen II'),
  ('The Unbreathing Queen III'),
  ('The Unbreathing Queen IV'),
  ('The Unbreathing Queen V'),
  ('The Warmongers I'),
  ('The Warmongers II'),
  ('The Warmongers III'),
  ('The Warmongers IV'),
  ('Unbearable Whispers I'),
  ('Unbearable Whispers II'),
  ('Unbearable Whispers III'),
  ('Unbearable Whispers IV'),
  ('Unbearable Whispers V');