INSERT INTO bases (name, height, width, class, drop_level)
  VALUES
  ('Ashscale Talisman', 1, 1, 'Talisman', 1),
  ('Black Maw Talisman', 1, 1, 'Talisman', 1),
  ('Bonespire Talisman', 1, 1, 'Talisman', 1),
  ('Breakrib Talisman', 1, 1, 'Talisman', 1),
  ('Chrysalis Talisman', 1, 1, 'Talisman', 1),
  ('Deadhand Talisman', 1, 1, 'Talisman', 1),
  ('Deep One Talisman', 1, 1, 'Talisman', 1),
  ('Lone Antler Talisman', 1, 1, 'Talisman', 1),
  ('Mandible Talisman', 1, 1, 'Talisman', 1),
  ('Rot Head Talisman', 1, 1, 'Talisman', 1),
  ('Undying Flesh Talisman', 1, 1, 'Talisman', 1),
  ('Writhing Talisman', 1, 1, 'Talisman', 1),
  ('Avian Twins Talisman', 1, 1, 'Talisman', 1),
  ('Clutching Talisman', 1, 1, 'Talisman', 1),
  ('Fangjaw Talisman', 1, 1, 'Talisman', 1),
  ('Hexclaw Talisman', 1, 1, 'Talisman', 1),
  ('Horned Talisman', 1, 1, 'Talisman', 1),
  ('Primal Skull Talisman', 1, 1, 'Talisman', 1),
  ('Splitnewt Talisman', 1, 1, 'Talisman', 1),
  ('Wereclaw Talisman', 1, 1, 'Talisman', 1),
  ('Longtooth Talisman', 1, 1, 'Talisman', 1),
  ('Monkey Paw Talisman', 1, 1, 'Talisman', 1),
  ('Monkey Twins Talisman', 1, 1, 'Talisman', 1),
  ('Rotfeather Talisman', 1, 1, 'Talisman', 1),
  ('Spinefuse Talisman', 1, 1, 'Talisman', 1),
  ('Three Hands Talisman', 1, 1, 'Talisman', 1),
  ('Three Rat Talisman', 1, 1, 'Talisman', 1),
  ('Greatwolf Talisman', 1, 1, 'Talisman', 1);