INSERT INTO bases (name, height, width, class, drop_level)
  VALUES
  ('Driftwood Maul', 4, 2, 'Two Handed Mace', 3),
  ('Tribal Maul', 4, 2, 'Two Handed Mace', 8),
  ('Mallet', 4, 2, 'Two Handed Mace', 12),
  ('Sledgehammer', 4, 2, 'Two Handed Mace', 17),
  ('Jagged Maul', 4, 2, 'Two Handed Mace', 22),
  ('Brass Maul', 4, 2, 'Two Handed Mace', 27),
  ('Fright Maul', 4, 2, 'Two Handed Mace', 32),
  ('Morning Star', 4, 2, 'Two Handed Mace', 34),
  ('Totemic Maul', 4, 2, 'Two Handed Mace', 36),
  ('Great Mallet', 4, 2, 'Two Handed Mace', 40),
  ('Steelhead', 4, 2, 'Two Handed Mace', 44),
  ('Spiny Maul', 4, 2, 'Two Handed Mace', 48),
  ('Plated Maul', 4, 2, 'Two Handed Mace', 51),
  ('Dread Maul', 4, 2, 'Two Handed Mace', 54),
  ('Solar Maul', 4, 2, 'Two Handed Mace', 56),
  ('Karui Maul', 4, 2, 'Two Handed Mace', 57),
  ('Colossus Mallet', 4, 2, 'Two Handed Mace', 59),
  ('Piledriver', 4, 2, 'Two Handed Mace', 61),
  ('Meatgrinder', 4, 2, 'Two Handed Mace', 63),
  ('Imperial Maul', 4, 2, 'Two Handed Mace', 65),
  ('Terror Maul', 4, 2, 'Two Handed Mace', 67),
  ('Coronal Maul', 4, 2, 'Two Handed Mace', 69);